/* Лента Instagram @relictum — единственный источник правды.
   Правится руками; всё остальное производное.
   Ритм 2+1: в каждой тройке слотов ровно один товарный пост (exhibit != null).
   Каждое число в facts обязано сверяться с паспортом: catalog.js по slug,
   promo-data.js по id вида R–0609, eras.js по слагу геологического
   подразделения (для датировок на карточках рубрики era). Не сверено —
   не публикуется. */
window.RELICTUM_FEED = [
  {
    id: 'p01',
    date: '2026-08-18',
    rubric: 'era',
    slot: 1,
    exhibit: null,
    format: 'carousel',
    frames: [
      { type: 'video', src: 'era_mammoth.mp4', crop: '4:5' },
      { type: 'card', tpl: 'era', data: { era: 'Плейстоцен', when: '2,6 млн — 11,7 тыс лет назад', fact: 'Мамонтовая степь тянулась от Испании до Юкона.' } },
      { type: 'card', tpl: 'end', data: {} },
    ],
    caption: { lead: 'Плейстоцен', body: 'Эпоха, в которой мамонтовая степь была самым обширным биомом планеты.', cta: '' },
    tags: ['#relictum', '#палеонтология', '#плейстоцен'],
    facts: [
      { claim: 'датировка эпохи', value: '2,6 млн — 11,7 тыс лет назад', source: 'eras.js:pleistocene.when', checked: true },
    ],
    status: 'ready',
    blockers: [],
  },
  {
    id: 'p02',
    date: '2026-08-20',
    rubric: 'figure',
    slot: 2,
    exhibit: null,
    format: 'single',
    frames: [
      { type: 'card', tpl: 'figure', data: { name: 'Сеймчан', big: '≈ 4,56 млрд лет', sub: 'Возраст вещества палласита — старше Земли.' } },
    ],
    caption: { lead: '4,56 миллиарда лет', body: 'Столько вещество палласита существует до того, как попасть в витрину.', cta: '' },
    tags: ['#relictum', '#метеорит'],
    facts: [
      { claim: 'возраст', value: '≈ 4,56 млрд лет', source: 'catalog.js:seymchan-pallasite.age', checked: true },
    ],
    status: 'ready',
    blockers: [],
  },
  {
    id: 'p03',
    date: '2026-08-22',
    rubric: 'object',
    slot: 3,
    exhibit: 'megalodon-tooth',
    format: 'carousel',
    frames: [
      { type: 'video', src: 'spin_megalodon.mp4', crop: '1:1' },
      { type: 'photo', src: 'int_ph_megalodon.jpg', crop: '4:5' },
      { type: 'card', tpl: 'spec', data: { name: 'Зуб мегалодона', rows: [['Возраст', '≈ 23 млн лет, миоцен'], ['Оформление', 'Стальной стенд']] } },
      { type: 'card', tpl: 'end', data: {} },
    ],
    caption: { lead: 'Зуб мегалодона', body: 'Эмаль сохранила цвет породы, в которой зуб пролежал миоцен целиком.', cta: 'Стоимость и наличие — по запросу в галерею.' },
    tags: ['#relictum', '#мегалодон'],
    facts: [
      { claim: 'возраст', value: '≈ 23 млн лет, миоцен', source: 'catalog.js:megalodon-tooth.age', checked: true },
      { claim: 'оформление', value: 'Стальной стенд', source: 'catalog.js:megalodon-tooth.mount', checked: true },
    ],
    status: 'ready',
    blockers: [],
  },
  {
    id: 'p04',
    date: '2026-08-24',
    rubric: 'figure',
    slot: 4,
    exhibit: null,
    format: 'single',
    frames: [
      { type: 'card', tpl: 'figure', data: { name: 'Dunkleosteus', big: '≈ 360 млн лет, поздний девон', sub: 'Возраст черепа панцирной рыбы позднего девона.' } },
    ],
    caption: { lead: '360 миллионов лет', body: 'Броневые пластины головы хищной панцирной рыбы девонского моря.', cta: '' },
    tags: ['#relictum', '#девон'],
    facts: [
      { claim: 'возраст', value: '≈ 360 млн лет, поздний девон', source: 'catalog.js:0219-dunkleosteus.age', checked: true },
    ],
    status: 'ready',
    blockers: [],
  },
  {
    id: 'p05',
    date: '2026-08-26',
    rubric: 'era',
    slot: 5,
    exhibit: null,
    format: 'carousel',
    frames: [
      { type: 'video', src: 'era_cretaceous.mp4', crop: '4:5' },
      { type: 'card', tpl: 'era', data: { era: 'Меловой период', when: '145 — 66 млн лет назад', fact: 'Последний период мезозоя закончился падением астероида на полуострове Юкатан.' } },
      { type: 'card', tpl: 'end', data: {} },
    ],
    caption: { lead: 'Меловой период', body: 'Последняя глава эры динозавров — самая долгая и самая разнообразная.', cta: '' },
    tags: ['#relictum', '#мел', '#палеонтология'],
    facts: [
      { claim: 'датировка периода', value: '145 — 66 млн лет назад', source: 'eras.js:cretaceous.when', checked: true },
    ],
    status: 'ready',
    blockers: [],
  },
  {
    id: 'p06',
    date: '2026-08-28',
    rubric: 'object',
    slot: 6,
    exhibit: 'mammoth-skull-tusks',
    format: 'carousel',
    frames: [
      { type: 'video', src: 'spin_mammoth_skull.mp4', crop: '1:1' },
      { type: 'photo', src: 'int_ph_mammoth_skull.jpg', crop: '4:5' },
      { type: 'card', tpl: 'spec', data: { name: 'Череп мамонта с бивнями', rows: [['Возраст', '≈ 30 000 лет'], ['Оформление', 'Гранитный блок, бронзовые опоры']] } },
      { type: 'card', tpl: 'end', data: {} },
    ],
    caption: { lead: 'Череп мамонта с бивнями', body: 'Размах бивней больше двух метров — предмет держит зал сам по себе.', cta: 'Стоимость и наличие — по запросу в галерею.' },
    tags: ['#relictum', '#мамонт'],
    facts: [
      { claim: 'возраст', value: '≈ 30 000 лет', source: 'catalog.js:mammoth-skull-tusks.age', checked: true },
      { claim: 'оформление', value: 'Гранитный блок, бронзовые опоры', source: 'catalog.js:mammoth-skull-tusks.mount', checked: true },
    ],
    status: 'ready',
    blockers: [],
  },
  {
    id: 'p07',
    date: '2026-08-30',
    rubric: 'era',
    slot: 7,
    exhibit: null,
    format: 'carousel',
    frames: [
      { type: 'video', src: 'era_paleozoic_sea.mp4', crop: '4:5' },
      { type: 'card', tpl: 'era', data: { era: 'Палеозойская эра', when: '539 — 252 млн лет назад', fact: 'Трилобиты и панцирные рыбы населяли тёплые мелководные шельфы.' } },
      { type: 'card', tpl: 'end', data: {} },
    ],
    caption: { lead: 'Палеозойская эра', body: 'Мелководные шельфы, где задолго до динозавров правили трилобиты.', cta: '' },
    tags: ['#relictum', '#палеозой'],
    facts: [
      { claim: 'датировка эры', value: '539 — 252 млн лет назад', source: 'eras.js:paleozoic.when', checked: true },
    ],
    status: 'ready',
    blockers: [],
  },
  {
    id: 'p08',
    date: '2026-09-01',
    rubric: 'figure',
    slot: 8,
    exhibit: null,
    format: 'single',
    frames: [
      { type: 'card', tpl: 'figure', data: { name: 'Трилобит', big: '≈ 480–472 млн лет, ранний ордовик', sub: 'Возраст гигантского трилобита раннего ордовика.' } },
    ],
    caption: { lead: '480 миллионов лет', body: 'Гигантский трилобит ордовикского моря — редкая величина для этой группы.', cta: '' },
    tags: ['#relictum', '#трилобит'],
    facts: [
      { claim: 'возраст', value: '≈ 480–472 млн лет, ранний ордовик', source: 'catalog.js:0217-dikelokephalina.age', checked: true },
    ],
    status: 'ready',
    blockers: [],
  },
  {
    id: 'p09',
    date: '2026-09-03',
    rubric: 'object',
    slot: 9,
    exhibit: '0611-coelodonta-skeleton',
    format: 'carousel',
    frames: [
      { type: 'video', src: 'spin_rhino_skeleton.mp4', crop: '1:1' },
      { type: 'photo', src: 'int_ph_rhino_skeleton.jpg', crop: '4:5' },
      { type: 'card', tpl: 'spec', data: { name: 'Скелет шерстистого носорога', rows: [['Возраст', '50–150 тыс лет, плейстоцен'], ['Оформление', 'Профессиональная сборка на скрытом каркасе']] } },
      { type: 'card', tpl: 'end', data: {} },
    ],
    caption: { lead: 'Скелет шерстистого носорога', body: 'Полный смонтированный костяк ледникового зверя плейстоцена.', cta: 'Стоимость и наличие — по запросу в галерею.' },
    tags: ['#relictum', '#носорог'],
    facts: [
      { claim: 'возраст', value: '50–150 тыс лет, плейстоцен', source: 'catalog.js:0611-coelodonta-skeleton.age', checked: true },
      { claim: 'оформление', value: 'Профессиональная сборка на скрытом каркасе', source: 'catalog.js:0611-coelodonta-skeleton.mount', checked: true },
    ],
    status: 'ready',
    blockers: [],
  },
  {
    id: 'p10',
    date: '2026-09-05',
    rubric: 'interior',
    slot: 10,
    exhibit: null,
    format: 'carousel',
    frames: [
      { type: 'photo', src: 'int_curiosity_wall.jpg', crop: '4:5' },
      { type: 'card', tpl: 'end', data: {} },
    ],
    caption: { lead: 'Интерьер галереи', body: 'Свет, сталь и тёмное дерево задают тон залам Relictum.', cta: '' },
    tags: ['#relictum', '#интерьер'],
    facts: [],
    status: 'ready',
    blockers: [],
  },
  {
    id: 'p11',
    date: '2026-09-07',
    rubric: 'figure',
    slot: 11,
    exhibit: null,
    format: 'single',
    frames: [
      { type: 'card', tpl: 'figure', data: { name: 'Кейхозавр', big: '≈ 245 млн лет, триасовый период', sub: 'Возраст скелета кейхозавра триасового периода.' } },
    ],
    caption: { lead: '245 миллионов лет', body: 'Морская рептилия раннего триаса, поднявшаяся вскоре после величайшего вымирания.', cta: '' },
    tags: ['#relictum', '#триас'],
    facts: [
      { claim: 'возраст', value: '≈ 245 млн лет, триасовый период', source: 'catalog.js:0212-keichousaurus-hui.age', checked: true },
    ],
    status: 'ready',
    blockers: [],
  },
  {
    id: 'p12',
    date: '2026-09-09',
    rubric: 'interior',
    slot: 12,
    exhibit: 'cave-bear-skeleton',
    format: 'carousel',
    frames: [
      { type: 'video', src: 'intv_cavebear.mp4', crop: '4:5' },
      { type: 'photo', src: 'g_cavebear_1.jpg', crop: '4:5' },
      { type: 'card', tpl: 'spec', data: { name: 'Скелет пещерного медведя', rows: [['Возраст', 'более 12 000 лет, плейстоцен'], ['Оформление', 'Стальной штырь на чернёном основании']] } },
      { type: 'card', tpl: 'end', data: {} },
    ],
    caption: { lead: 'Скелет пещерного медведя', body: 'Почти три метра длины — экспонат держит пространство просторного холла.', cta: 'Стоимость и наличие — по запросу в галерею.' },
    tags: ['#relictum', '#пещерныймедведь'],
    facts: [
      { claim: 'возраст', value: 'более 12 000 лет, плейстоцен', source: 'catalog.js:cave-bear-skeleton.age', checked: true },
      { claim: 'оформление', value: 'Стальной штырь на чернёном основании', source: 'catalog.js:cave-bear-skeleton.mount', checked: true },
    ],
    status: 'ready',
    blockers: [],
  },
  {
    id: 'p13',
    date: '2026-09-11',
    rubric: 'era',
    slot: 13,
    exhibit: null,
    format: 'carousel',
    frames: [
      { type: 'video', src: 'era_hadean.mp4', crop: '4:5' },
      { type: 'card', tpl: 'era', data: { era: 'Катархей', when: '4,6 — 4 млрд лет назад', fact: 'Древнейший эон Земли. Целых пород той эпохи не сохранилось — редкое исключение: цирконы Джек-Хиллз в Австралии, почти до 4,4 млрд лет.' } },
      { type: 'card', tpl: 'end', data: {} },
    ],
    caption: { lead: 'Катархей', body: 'Самый ранний эон планеты. Целых пород катархея на Земле не осталось — сохранились лишь отдельные минералы, кристаллы циркона возрастом почти до 4,4 млрд лет.', cta: '' },
    tags: ['#relictum', '#цирконы', '#космос'],
    facts: [
      { claim: 'датировка эона', value: '4,6 — 4 млрд лет назад', source: 'eras.js:hadean.when', checked: true },
    ],
    status: 'ready',
    blockers: [],
  },
  {
    id: 'p14',
    date: '2026-09-13',
    rubric: 'ritual',
    slot: 14,
    exhibit: null,
    format: 'carousel',
    frames: [
      { type: 'photo', src: 'pack_leather_box_open.jpg', crop: '4:5' },
      { type: 'card', tpl: 'end', data: {} },
    ],
    caption: { lead: 'Передача экспоната', body: 'Упаковка, документы и приёмка — свой ритуал для каждого предмета.', cta: '' },
    tags: ['#relictum', '#ритуал'],
    facts: [],
    status: 'ready',
    blockers: [],
  },
  {
    id: 'p15',
    date: '2026-09-15',
    rubric: 'object',
    slot: 15,
    exhibit: '0617-mammoth-skeleton',
    format: 'carousel',
    frames: [
      { type: 'video', src: 'spin_mammoth_skeleton.mp4', crop: '1:1' },
      { type: 'photo', src: 'int_ph_mammoth_skeleton.jpg', crop: '4:5' },
      { type: 'card', tpl: 'spec', data: { name: 'Скелет мамонта', rows: [['Возраст', '2,6 млн – 11 тыс лет, плейстоцен'], ['Оформление', 'Скрытый стальной каркас, монтаж на месте']] } },
      { type: 'card', tpl: 'end', data: {} },
    ],
    caption: { lead: 'Скелет мамонта', body: 'Полный смонтированный костяк ледникового гиганта — доминанта большого зала.', cta: 'Стоимость и наличие — по запросу в галерею.' },
    tags: ['#relictum', '#мамонт'],
    facts: [
      { claim: 'возраст', value: '2,6 млн – 11 тыс лет, плейстоцен', source: 'catalog.js:0617-mammoth-skeleton.age', checked: true },
      { claim: 'оформление', value: 'Скрытый стальной каркас, монтаж на месте', source: 'catalog.js:0617-mammoth-skeleton.mount', checked: true },
    ],
    status: 'ready',
    blockers: [],
  },
];
