window.RELICTUM_CATALOG = [
  {
    "id": "R–0101",
    "href": "../16_product_promos/exhibit.html?id=seymchan-pallasite",
    "world": "cosmos",
    "worldLabel": "Космос",
    "category": "Метеориты",
    "period": "До зарождения жизни",
    "era": "До зарождения жизни",
    "region": "Россия",
    "name": "Палласит Сеймчан",
    "latin": "Seymchan Pallasite",
    "meta": "Магаданская область, Россия, ≈ 4,56 млрд лет<br>Срез 18 × 14 см, 1 240 г",
    "price": "2 400 000 ₽",
    "img": "ph_seymchan",
    "priceValue": 2400000,
    "slug": "seymchan-pallasite",
    "age": "≈ 4,56 млрд лет",
    "location": "Магаданская область, Россия",
    "found": "1967 г.",
    "size": "Срез 18 × 14 см, 1 240 г",
    "mount": "Стальная подставка",
    "description": "Полированный срез железно-каменного метеорита с кристаллами оливина, застывшими в никелистом железе. Палласиты — вещество границы ядра и мантии разрушенной протопланеты; старше самой Земли.",
    "status": "Под заказ",
    "hidden": true
  },
  {
    "id": "R–0272",
    "world": "grand",
    "worldLabel": "Монументы",
    "category": "Динозавры",
    "period": "Мел",
    "era": "Мезозой",
    "region": "—",
    "latin": "Dromaeosauridae indet.",
    "name": "Скелет дромеозаврида",
    "meta": "Поздний мел<br>Под заказ",
    "price": "Цена по запросу",
    "img": "ph_raptor",
    "priceValue": null,
    "status": "Под заказ",
    "slug": "0272-dromaeosaurid",
    "age": "поздний мел",
    "location": "",
    "size": "Длина 1,2 м",
    "mount": "Монтаж на опоре из чернёной стали (выполняется домом)",
    "description": "Скелет хищного динозавра из группы дромеозаврид — «рапторов». Экземпляр хранится в разобранном виде и требует небольшой реставрации; поставляется под заказ.",
    "href": "../16_product_promos/exhibit.html?id=0272-dromaeosaurid"
  },
  {
    "id": "R–0103",
    "world": "cosmos",
    "worldLabel": "Космос",
    "category": "Метеориты",
    "period": "До зарождения жизни",
    "era": "До зарождения жизни",
    "region": "Россия",
    "name": "Метеорит Дронино",
    "latin": "Dronino Iron",
    "meta": "Рязанская область, Россия, ≈ 4,5 млрд лет",
    "price": "6 000 000 ₽",
    "img": "ph_dronino",
    "priceValue": 6000000,
    "slug": "0103-dronino-iron",
    "age": "≈ 4,5 млрд лет",
    "location": "Рязанская область, Россия",
    "found": "2000 г.",
    "size": "13 × 9 × 26 см, вес 7,4 кг",
    "mount": "Оформление по запросу клиента",
    "description": "Железный метеорит-атаксит с глубоким рельефом регмаглиптов — следами оплавления в атмосфере. Индивидуалы Дронино ценятся за «дикую», ничем не тронутую форму.",
    "href": "../16_product_promos/meteorite-dronino.html"
  },
  {
    "id": "R–0271",
    "world": "grand",
    "worldLabel": "Монументы",
    "category": "Динозавры",
    "period": "Мел",
    "era": "Мезозой",
    "region": "США",
    "latin": "Triceratops sp.",
    "name": "Череп трицератопса",
    "meta": "Поздний мел, Северная Америка<br>По предзаказу",
    "price": "Цена по запросу",
    "img": "ph_triceratops",
    "priceValue": null,
    "status": "Под заказ",
    "slug": "0271-triceratops-skull",
    "age": "≈ 68–66 млн лет, поздний мел (маастрихт)",
    "location": "Северная Америка",
    "size": "По запросу",
    "mount": "Мощение на опоре из чернёной стали",
    "description": "Череп трицератопса с полным воротником и обоими надглазничными рогами. Объект ожидается в коллекции и открыт по предзаказу.",
    "href": "../16_product_promos/exhibit.html?id=0271-triceratops-skull"
  },
  {
    "id": "R–0104",
    "world": "cosmos",
    "worldLabel": "Космос",
    "category": "Метеориты",
    "period": "До зарождения жизни",
    "era": "До зарождения жизни",
    "region": "Россия",
    "name": "Метеорит Чинге",
    "latin": "Chinga Iron",
    "meta": "Чинге, Тыва, Россия, ≈ 4,5 млрд лет",
    "price": "Цена по запросу",
    "img": "ph_chinge",
    "priceValue": null,
    "slug": "0104-chinga-iron",
    "age": "≈ 4,5 млрд лет",
    "location": "Река Чинге, Тыва, Россия",
    "size": "По запросу",
    "mount": "Музейная стойка",
    "description": "Богатый никелем железный метеорит (атаксит) с тёмной корой. Экспонируется на музейной стойке; скульптурная форма обломка не повторяется ни у одного другого.",
    "href": "../16_product_promos/meteorite-chinge.html",
    "status": "Под заказ"
  },
  {
    "id": "R–0246",
    "world": "terra",
    "worldLabel": "Земля",
    "category": "Минералы",
    "region": "Мадагаскар",
    "latin": "Celestine, SrSO₄",
    "name": "Целестин",
    "meta": "Кристаллы музейного уровня, Мадагаскар",
    "price": "Цена по запросу",
    "img": "ph_celestine",
    "priceValue": null,
    "slug": "0246-celestine",
    "location": "Sakoany deposit, Мадагаскар",
    "size": "Около 20 × 17 × 13,5 см",
    "description": "Целестин крайне редко образует кристаллы такого размера.",
    "href": "../16_product_promos/exhibit.html?id=0246-celestine"
  },
  {
    "id": "R–0105",
    "world": "cosmos",
    "worldLabel": "Космос",
    "category": "Метеориты",
    "period": "До зарождения жизни",
    "era": "До зарождения жизни",
    "region": "Луна",
    "name": "Лунный метеорит в раме",
    "latin": "Lunar meteorite",
    "meta": "Луна, ≈ 4,5 млрд лет",
    "price": "Цена по запросу",
    "img": "ph_moon_frame",
    "priceValue": null,
    "slug": "0105-lunar-meteorite",
    "age": "≈ 4,5 млрд лет",
    "location": "Лунная поверхность, выброшен ударом астероида",
    "size": "По запросу",
    "mount": "Кабинетная рама, настольная или настенная",
    "description": "Обломок лунной коры, выбитый в космос ударом астероида и упавший на Землю, — в одной раме с фотографией полной Луны.",
    "href": "../16_product_promos/lunar-frame.html",
    "qty": "Десять экземпляров"
  },
  {
    "id": "R–0231",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Морские лилии",
    "period": "Триас",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Морская лилия",
    "latin": "Traumatocrinus guanlingensis",
    "meta": "Раскрытый веер, Китай, триас<br>Под заказ",
    "price": "Цена по запросу",
    "img": "ph_crinoid_fan",
    "priceValue": null,
    "slug": "0231-crinoid-fan",
    "age": "≈ 235 млн лет, триас",
    "location": "Юньнань-Гуйчжоу, Китай",
    "size": "По запросу",
    "mount": "Плита на стальной подставке",
    "status": "Под заказ",
    "description": "Крупный раскрытый веер Traumatocrinus на цельной плите — парадный экземпляр серии.",
    "href": "../16_product_promos/exhibit.html?id=0231-crinoid-fan"
  },
  {
    "id": "R–0227",
    "world": "cosmos",
    "worldLabel": "Космос",
    "category": "Метеориты",
    "period": "До зарождения жизни",
    "era": "До зарождения жизни",
    "region": "Россия",
    "name": "Метеорит Дронино, 128 кг",
    "latin": "Dronino Iron",
    "meta": "Рязанская область, Россия, ≈ 4,5 млрд лет<br>128 кг",
    "price": "Цена по запросу",
    "img": "ph_dronino128",
    "priceValue": null,
    "slug": "0227-dronino-128kg",
    "age": "≈ 4,5 млрд лет",
    "location": "Рязанская область, Россия",
    "size": "128 кг",
    "mount": "Массивный металлический постамент",
    "description": "Железный метеорит Дронино массой сто двадцать восемь килограммов — один из самых крупных найденных экземпляров этого падения. Монументальный объект космического происхождения на авторской подставке.",
    "href": "../16_product_promos/exhibit.html?id=0227-dronino-128kg",
    "status": "Под заказ"
  },
  {
    "id": "R–0609",
    "world": "grand",
    "worldLabel": "Монументы",
    "category": "Динозавры",
    "period": "Мел",
    "era": "Мезозой",
    "region": "Китай",
    "latin": "Jeholosaurus shangyuanensis",
    "name": "Скелет жехолозавра",
    "meta": "Ляонин, Китай, ранний мел<br>Под заказ",
    "price": "Цена по запросу",
    "img": "ph_jeholosaurus",
    "priceValue": null,
    "status": "Под заказ",
    "slug": "0609-jeholosaurus",
    "age": "≈ 125 млн лет, ранний мел",
    "location": "Провинция Ляонин, Китай",
    "size": "Длина 70 см",
    "mount": "Монтаж на опоре из чернёной стали (выполняется домом)",
    "description": "Полный скелет мелкого растительноядного динозавра Jeholosaurus из формации Исянь. Экземпляр хранится в разобранном виде и поставляется под заказ — сборка и монтаж на опоре выполняются домом.",
    "href": "../16_product_promos/exhibit.html?id=0609-jeholosaurus"
  },
  {
    "id": "R–0276",
    "world": "cosmos",
    "worldLabel": "Космос",
    "category": "Метеориты",
    "period": "До зарождения жизни",
    "era": "До зарождения жизни",
    "region": "Китай",
    "latin": "Aletai Iron",
    "name": "Срез метеорита Алетай",
    "meta": "Алтайские горы, Китай, ≈ 4,5 млрд лет",
    "price": "2 000 000 ₽",
    "img": "ph_met_aletai",
    "priceValue": 2000000,
    "slug": "0276-aletai-slice",
    "age": "≈ 4,5 млрд лет",
    "location": "Алтайские горы, Китай",
    "size": "Вес 9 895 г",
    "mount": "Чернёная сталь",
    "description": "Полированный срез железного метеорита Алетай весом почти десять килограммов. На плоскости проступает узор Видманштеттена — сетка кристаллов никелистого железа, выросшая при остывании в недрах космического тела.",
    "href": "../16_product_promos/exhibit.html?id=0276-aletai-slice"
  },
  {
    "id": "R–0247",
    "world": "terra",
    "worldLabel": "Земля",
    "category": "Минералы",
    "region": "ДР Конго",
    "latin": "Pseudomalachite",
    "name": "Псевдомалахит",
    "meta": "Редкий минерал, ДР Конго",
    "price": "Цена по запросу",
    "img": "ph_pseudomalachite",
    "priceValue": null,
    "slug": "0247-pseudomalachite",
    "location": "L'Etoile du Congo Mine, Лубумбаши, ДР Конго",
    "size": "Около 30 × 24 × 23,5 см, вес 8,7 кг",
    "mount": "Акриловый постамент",
    "description": "Редкий минерал; образцы такого размера — особенная редкость.",
    "href": "../16_product_promos/exhibit.html?id=0247-pseudomalachite"
  },
  {
    "id": "R–0277",
    "world": "cosmos",
    "worldLabel": "Космос",
    "category": "Метеориты",
    "period": "До зарождения жизни",
    "era": "До зарождения жизни",
    "region": "Китай",
    "latin": "Aletai Iron",
    "name": "Куб из метеорита Алетай",
    "meta": "Алтайские горы, Китай, 1 267 г",
    "price": "380 100 ₽",
    "img": "ph_met_aletai_cubes",
    "priceValue": 380100,
    "slug": "0277-aletai-cube",
    "age": "≈ 4,5 млрд лет",
    "location": "Алтайские горы, Китай",
    "size": "Вес 1 267 г",
    "mount": "Чернёная сталь",
    "description": "Куб, вырезанный из фрагмента железного метеорита Алетай и отполированный по всем граням: на каждой видны видманштеттеновы фигуры.",
    "href": "../16_product_promos/exhibit.html?id=0277-aletai-cube"
  },
  {
    "id": "R–0232",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Морские лилии",
    "period": "Триас",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Морская лилия",
    "latin": "Traumatocrinus guanlingensis",
    "meta": "Круглая крона, Китай, триас<br>Под заказ",
    "price": "Цена по запросу",
    "img": "ph_crinoid_round",
    "priceValue": null,
    "slug": "0232-crinoid-round",
    "age": "≈ 235 млн лет, триас",
    "location": "Юньнань-Гуйчжоу, Китай",
    "size": "По запросу",
    "mount": "Плита на стальной подставке",
    "status": "Под заказ",
    "description": "Редкая подача: крона раскрыта полным кругом, руки читаются до кончиков.",
    "href": "../16_product_promos/exhibit.html?id=0232-crinoid-round"
  },
  {
    "id": "R–0278",
    "world": "cosmos",
    "worldLabel": "Космос",
    "category": "Метеориты",
    "period": "До зарождения жизни",
    "era": "До зарождения жизни",
    "region": "Китай",
    "latin": "Aletai Iron",
    "name": "Шар из метеорита Алетай",
    "meta": "Алтайские горы, Китай, ≈ 4,5 млрд лет",
    "price": "901 500 ₽",
    "img": "ph_met_aletai_sphere",
    "priceValue": 901500,
    "slug": "0278-aletai-sphere",
    "age": "≈ 4,5 млрд лет",
    "location": "Алтайские горы, Китай",
    "size": "Вес 3 005 г",
    "mount": "Чернёная сталь",
    "description": "Шар, выточенный из фрагмента железного метеорита Алетай. Узор Видманштеттена идёт по всей окружности — рисунок кристаллов никелистого железа, который формируется только при космически медленном остывании.",
    "href": "../16_product_promos/exhibit.html?id=0278-aletai-sphere"
  },
  {
    "id": "R–0610",
    "href": "../16_product_promos/exhibit.html?id=0610-psittacosaurus-skeleton",
    "world": "grand",
    "worldLabel": "Монументы",
    "category": "Динозавры",
    "period": "Мел",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Скелет пситтакозавра",
    "latin": "Psittacosaurus sp.",
    "meta": "Ляонин, Китай, ≈ 125 млн лет<br>168 см",
    "price": "7 500 000 ₽",
    "img": "ph_psittacosaurus_skeleton",
    "priceValue": 7500000,
    "slug": "0610-psittacosaurus-skeleton",
    "age": "≈ 125 млн лет, ранний мел",
    "location": "Провинция Ляонин, Китай",
    "size": "Смонтированный скелет 1,65 м — крупный для вида; комплектность более 95 %",
    "mount": "Музейная арматура",
    "description": "Полный смонтированный скелет Psittacosaurus sp. — раннего цератопса длиной 168 см. Высокий короткий череп, клювовидные челюсти и длинные задние конечности; комплектность превышает 95 %, подготовка и монтаж рассчитаны на постоянное экспонирование."
  },
  {
    "id": "R–0279",
    "world": "cosmos",
    "worldLabel": "Космос",
    "category": "Метеориты",
    "period": "До зарождения жизни",
    "era": "До зарождения жизни",
    "region": "Китай",
    "latin": "Aletai Iron",
    "name": "Малый шар из метеорита Алетай",
    "meta": "Алтайские горы, Китай, ≈ 300 г",
    "price": "90 000 ₽",
    "img": "ph_met_aletai_ball",
    "priceValue": 90000,
    "slug": "0279-aletai-spheres-small",
    "age": "≈ 4,5 млрд лет",
    "location": "Алтайские горы, Китай",
    "size": "Вес около 300 г",
    "mount": "Чернёная сталь",
    "description": "Шар, выточенный из фрагмента железного метеорита Алетай, около трёхсот граммов. По всей окружности видны видманштеттеновы фигуры. В доме шесть одинаковых шаров, цена указана за один.",
    "href": "../16_product_promos/exhibit.html?id=0279-aletai-spheres-small",
    "qty": "Шесть шаров"
  },
  {
    "id": "R–0248",
    "world": "terra",
    "worldLabel": "Земля",
    "category": "Минералы",
    "region": "Перу",
    "latin": "Pyrite, FeS₂",
    "name": "Пирит",
    "meta": "Сросток кубических кристаллов, Перу",
    "price": "Цена по запросу",
    "img": "ph_pyrite",
    "priceValue": null,
    "slug": "0248-pyrite",
    "location": "Huanzala Mine, Анкаш, Перу",
    "size": "Около 28 × 17,5 × 13,5 см, вес 10,8 кг",
    "mount": "Чёрное основание с латунной табличкой",
    "description": "Десять крупных кубов и сотня кристаллов поменьше — геометрия, которую природа собрала сама.",
    "href": "../16_product_promos/exhibit.html?id=0248-pyrite"
  },
  {
    "id": "R–0280",
    "world": "cosmos",
    "worldLabel": "Космос",
    "category": "Метеориты",
    "period": "До зарождения жизни",
    "era": "До зарождения жизни",
    "region": "Россия",
    "latin": "Kainsaz CO3",
    "name": "Метеорит Каинсаз",
    "meta": "Татарстан, Россия, 685 г",
    "price": "2 740 000 ₽",
    "img": "ph_met_kainsaz_a",
    "priceValue": 2740000,
    "slug": "0280-kainsaz",
    "age": "≈ 4,59 млрд лет",
    "location": "Татарстан, Россия",
    "size": "Вес 685 г",
    "mount": "Чернёная сталь",
    "description": "Углистый хондрит — вещество, которое старше Земли примерно на пятьдесят миллионов лет и сохранило органические соединения ранней Солнечной системы.",
    "href": "../16_product_promos/exhibit.html?id=0280-kainsaz"
  },
  {
    "id": "R–0233",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Морские лилии",
    "period": "Триас",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Морская лилия",
    "latin": "Traumatocrinus guanlingensis",
    "meta": "Веер в раме, Китай, триас<br>Под заказ",
    "price": "Цена по запросу",
    "img": "ph_crinoid_frame_fan",
    "priceValue": null,
    "slug": "0233-crinoid-frame-fan",
    "age": "≈ 235 млн лет, триас",
    "location": "Юньнань-Гуйчжоу, Китай",
    "size": "По запросу",
    "mount": "Деревянная рама",
    "status": "Под заказ",
    "description": "Веер на прямом стебле в деревянной раме — готовый кабинетный объект.",
    "href": "../16_product_promos/exhibit.html?id=0233-crinoid-frame-fan"
  },
  {
    "id": "R–0281",
    "world": "cosmos",
    "worldLabel": "Космос",
    "category": "Метеориты",
    "period": "До зарождения жизни",
    "era": "До зарождения жизни",
    "region": "Оман",
    "latin": "Dhofar",
    "name": "Метеорит Dhofar",
    "meta": "Дофар, Оман, ≈ 4,5 млрд лет",
    "price": "571 000 ₽",
    "img": "ph_met_dhofar",
    "priceValue": 571000,
    "slug": "0281-dhofar",
    "age": "≈ 4,5 млрд лет",
    "location": "Дофар, Оман",
    "size": "Вес 1 142 г",
    "mount": "Чернёная сталь",
    "description": "Метеорит весом 1 142 грамма, найденный в пустыне Дофар в Омане. Поверхность несёт следы долгого пребывания в пустыне — тёмная кора и охристый налёт у основания.",
    "href": "../16_product_promos/exhibit.html?id=0281-dhofar"
  },
  {
    "id": "R–0613",
    "world": "grand",
    "worldLabel": "Монументы",
    "category": "Динозавры",
    "period": "Мел",
    "era": "Мезозой",
    "region": "Монголия",
    "name": "Скелет пинакозавра",
    "latin": "Pinacosaurus",
    "meta": "Центральная Азия, около 80–75 млн лет",
    "price": "Цена по запросу",
    "img": "ph_pinacosaurus",
    "priceValue": null,
    "slug": "0613-pinacosaurus",
    "age": "около 80–75 млн лет, поздний мел",
    "location": "Центральная Азия",
    "size": "По запросу",
    "mount": "Низкая плита из чернёной стали, вертикальные стойки",
    "description": "Смонтированный скелет пинакозавра — панцирного динозавра (анкилозавра) позднего мела. Костные пластины-остеодермы вдоль спины и характерный низкий силуэт; скелет смонтирован на скрытом стальном каркасе.",
    "href": "../16_product_promos/exhibit.html?id=0613-pinacosaurus",
    "status": "Под заказ"
  },
  {
    "id": "R–0282",
    "world": "cosmos",
    "worldLabel": "Космос",
    "category": "Метеориты",
    "period": "До зарождения жизни",
    "era": "До зарождения жизни",
    "region": "Россия",
    "latin": "Ozerki L6",
    "name": "Метеорит Озерки",
    "meta": "Липецкая область, Россия, 182 г",
    "price": "546 000 ₽",
    "img": "ph_met_ozerki_a",
    "priceValue": 546000,
    "slug": "0282-ozerki",
    "age": "≈ 4,5 млрд лет",
    "location": "Липецкая область, Россия",
    "size": "Вес 182 г",
    "mount": "Чернёная сталь",
    "description": "Камень собран сразу после падения — поэтому на нём сохранилась первичная кора плавления, тонкая чёрная плёнка, застывшая за секунды прохождения через атмосферу.",
    "href": "../16_product_promos/exhibit.html?id=0282-ozerki"
  },
  {
    "id": "R–0249",
    "world": "terra",
    "worldLabel": "Земля",
    "category": "Минералы",
    "region": "Бразилия",
    "latin": "Quartz var. amethyst",
    "name": "Аметист",
    "meta": "Друза на постаменте 45 × 25 × 15,5 см, Бразилия",
    "price": "Цена по запросу",
    "img": "ph_amethyst_druse45",
    "priceValue": null,
    "slug": "0249-amethyst-druse45",
    "location": "Ametista do Sul, Риу-Гранди-ду-Сул, Бразилия",
    "size": "Друза около 31,5 × 25 × 6,5 см, вес 9,2 кг; с постаментом 45 × 25 × 15,5 см",
    "mount": "Постамент",
    "description": "Три генерации кварца в одном образце: агат, бесцветный кварц и фиолетовый аметист.",
    "href": "../16_product_promos/exhibit.html?id=0249-amethyst-druse45"
  },
  {
    "id": "R–0283",
    "world": "cosmos",
    "worldLabel": "Космос",
    "category": "Метеориты",
    "period": "До зарождения жизни",
    "era": "До зарождения жизни",
    "region": "Россия",
    "latin": "Seymchan Pallasite",
    "name": "Палласит Сеймчан",
    "meta": "Магаданская область, Россия, ≈ 4,56 млрд лет",
    "price": "5 900 000 ₽",
    "img": "ph_met_seymchan3815",
    "priceValue": 5900000,
    "slug": "0283-seymchan-3815",
    "age": "≈ 4,56 млрд лет",
    "location": "Магаданская область, Россия",
    "size": "Вес 3 815 г",
    "mount": "Чернёная сталь",
    "description": "Полированный спил палласита Сеймчан: металлическая сетка никелистого железа, в которой сидят зёрна оливина. Вещество родилось на границе ядра и мантии разрушенной протопланеты. Крупный спил весом почти четыре килограмма.",
    "href": "../16_product_promos/exhibit.html?id=0283-seymchan-3815"
  },
  {
    "id": "R–0234",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Морские лилии",
    "period": "Триас",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Морская лилия",
    "latin": "Traumatocrinus guanlingensis",
    "meta": "Бутон в раме, Китай, триас<br>Под заказ",
    "price": "Цена по запросу",
    "img": "ph_crinoid_bud",
    "priceValue": null,
    "slug": "0234-crinoid-bud",
    "age": "≈ 235 млн лет, триас",
    "location": "Юньнань-Гуйчжоу, Китай",
    "size": "По запросу",
    "mount": "Деревянная рама",
    "status": "Под заказ",
    "description": "Сомкнутая крона на изящно изогнутом стебле — самый графичный экземпляр серии.",
    "href": "../16_product_promos/exhibit.html?id=0234-crinoid-bud"
  },
  {
    "id": "R–0604",
    "href": "../16_product_promos/exhibit.html?id=cave-bear-skeleton",
    "world": "grand",
    "worldLabel": "Монументы",
    "category": "Мамонтовая фауна",
    "period": "Плейстоцен",
    "era": "Кайнозой",
    "region": "Европа",
    "name": "Скелет пещерного медведя",
    "latin": "Ursus spelaeus",
    "meta": "Россия, более 12 000 лет<br>Длина 295 см, вес около 150 кг",
    "price": "7 500 000 ₽",
    "img": "ph_cavebear",
    "priceValue": 7500000,
    "slug": "cave-bear-skeleton",
    "age": "более 12 000 лет, плейстоцен",
    "location": "Россия",
    "size": "Длина 295 см, вес около 150 кг",
    "mount": "Стальной штырь на чернёном основании",
    "description": "Полный смонтированный скелет пещерного медведя — доисторического вида, вымершего около 15 000 лет назад. Высота почти три метра делает наш экземпляр одним из крупнейших представителей вида."
  },
  {
    "id": "R–0284",
    "world": "cosmos",
    "worldLabel": "Космос",
    "category": "Метеориты",
    "period": "До зарождения жизни",
    "era": "До зарождения жизни",
    "region": "Россия",
    "latin": "Seymchan Pallasite",
    "name": "Палласит Сеймчан",
    "meta": "Магаданская область, Россия, ≈ 4,56 млрд лет",
    "price": "1 400 000 ₽",
    "img": "ph_met_seymchan28x31",
    "priceValue": 1400000,
    "slug": "0284-seymchan-28x31",
    "age": "≈ 4,56 млрд лет",
    "location": "Магаданская область, Россия",
    "size": "28 × 31 см",
    "mount": "Чернёная сталь",
    "description": "Полированный спил палласита Сеймчан: металлическая сетка никелистого железа, в которой сидят зёрна оливина. Вещество родилось на границе ядра и мантии разрушенной протопланеты. Широкий спил 28 × 31 см.",
    "href": "../16_product_promos/exhibit.html?id=0284-seymchan-28x31"
  },
  {
    "id": "R–0614",
    "world": "grand",
    "worldLabel": "Монументы",
    "category": "Динозавры",
    "period": "Мел",
    "era": "Мезозой",
    "region": "Монголия",
    "name": "Скелет овираптора",
    "latin": "Oviraptoridae",
    "meta": "Центральная Азия, 89,8–70,6 млн лет",
    "price": "Цена по запросу",
    "img": "ph_oviraptor",
    "priceValue": null,
    "slug": "0614-oviraptor",
    "age": "89,8–70,6 млн лет, поздний мел",
    "location": "Центральная Азия",
    "size": "По запросу",
    "mount": "Музейная арматура",
    "description": "Полный смонтированный скелет овираптора — пернатого динозавра-теропода позднего мела с характерным беззубым клювом и лёгким сложением. Динамичная поза, музейный монтаж.",
    "href": "../16_product_promos/exhibit.html?id=0614-oviraptor",
    "status": "Под заказ"
  },
  {
    "id": "R–0250",
    "world": "terra",
    "worldLabel": "Земля",
    "category": "Минералы",
    "region": "Китай",
    "latin": "Fluorite & Pyrite",
    "name": "Флюорит с пиритом",
    "meta": "На постаменте 50 × 36 × 15,5 см, Китай",
    "price": "Цена по запросу",
    "img": "ph_fluorite_pyrite",
    "priceValue": null,
    "slug": "0250-fluorite-pyrite",
    "location": "Иу, Чжэцзян, Китай",
    "size": "Около 48,5 × 29 × 10 см, вес 26,8 кг",
    "mount": "Акриловый постамент",
    "description": "Фиолетовая гора, присыпанная золотом пирита.",
    "href": "../16_product_promos/exhibit.html?id=0250-fluorite-pyrite"
  },
  {
    "id": "R–0235",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Морские лилии",
    "period": "Триас",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Морская лилия",
    "latin": "Traumatocrinus guanlingensis",
    "meta": "Высокий веер в раме, Китай, триас<br>Под заказ",
    "price": "Цена по запросу",
    "img": "ph_crinoid_tall",
    "priceValue": null,
    "slug": "0235-crinoid-tall",
    "age": "≈ 235 млн лет, триас",
    "location": "Юньнань-Гуйчжоу, Китай",
    "size": "По запросу",
    "mount": "Деревянная рама",
    "status": "Под заказ",
    "description": "Высокая вертикальная композиция: веер венчает стебель во всю плиту.",
    "href": "../16_product_promos/exhibit.html?id=0235-crinoid-tall"
  },
  {
    "id": "R–0605",
    "href": "../16_product_promos/exhibit.html?id=mammoth-skull-tusks",
    "world": "grand",
    "worldLabel": "Монументы",
    "category": "Мамонтовая фауна",
    "period": "Плейстоцен",
    "era": "Кайнозой",
    "region": "Россия",
    "name": "Череп мамонта с бивнями",
    "latin": "Mammuthus primigenius",
    "meta": "Якутия, Россия, ≈ 30 000 лет<br>Размах бивней 2,4 м",
    "price": "7 400 000 ₽",
    "img": "ph_mammoth_skull",
    "priceValue": 7400000,
    "slug": "mammoth-skull-tusks",
    "age": "≈ 30 000 лет",
    "location": "Якутия, Россия",
    "size": "Размах бивней 2,4 м",
    "mount": "Гранитный блок, бронзовые опоры",
    "description": "Череп с полной парой бивней карамельной патины из вечной мерзлоты. Легальное происхождение, полный пакет экспертиз.",
    "status": "Под заказ"
  },
  {
    "id": "R–0285",
    "world": "cosmos",
    "worldLabel": "Космос",
    "category": "Метеориты",
    "period": "До зарождения жизни",
    "era": "До зарождения жизни",
    "region": "Россия",
    "latin": "Seymchan Pallasite",
    "name": "Палласит Сеймчан",
    "meta": "Магаданская область, Россия, ≈ 4,56 млрд лет",
    "price": "1 900 000 ₽",
    "img": "ph_met_seymchan28x25",
    "priceValue": 1900000,
    "slug": "0285-seymchan-28x25",
    "age": "≈ 4,56 млрд лет",
    "location": "Магаданская область, Россия",
    "size": "28 × 25 см",
    "mount": "Чернёная сталь",
    "description": "Полированный спил палласита Сеймчан: металлическая сетка никелистого железа, в которой сидят зёрна оливина. Вещество родилось на границе ядра и мантии разрушенной протопланеты. Спил 28 × 25 см с крупными зёрнами оливина.",
    "href": "../16_product_promos/exhibit.html?id=0285-seymchan-28x25"
  },
  {
    "id": "R–0213",
    "href": "../16_product_promos/exhibit.html?id=0213-psittacosaurus-skull",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Динозавры",
    "period": "Мел",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Череп пситтакозавра",
    "latin": "Psittacosaurus sp.",
    "meta": "Ляонин, Китай, ≈ 125 млн лет<br>Череп ≈ 15 см",
    "price": "1 690 000 ₽",
    "img": "ph_psittacosaurus_skull",
    "priceValue": 1690000,
    "slug": "0213-psittacosaurus-skull",
    "age": "≈ 125 млн лет, ранний мел",
    "location": "Провинция Ляонин, Китай",
    "size": "Череп ≈ 15 см",
    "mount": "Музейная стойка",
    "description": "Череп небольшого растительноядного динозавра Psittacosaurus sp. из группы ранних цератопсов. Высокий короткий череп, клювовидная передняя часть челюстей и выступающие скуловые элементы — характерный портрет «попугайного ящера» раннего мела."
  },
  {
    "id": "R–0254",
    "world": "terra",
    "worldLabel": "Земля",
    "category": "Минералы",
    "region": "Уругвай",
    "latin": "Quartz var. amethyst",
    "name": "Аметист",
    "meta": "Друза на подставке 35 × 11,2 × 9,8 см, Уругвай",
    "price": "Цена по запросу",
    "img": "ph_amethyst_druse35",
    "priceValue": null,
    "slug": "0254-amethyst-druse35",
    "location": "Артигас, Уругвай",
    "size": "35 × 11,2 × 9,8 см, вес 3,2 кг",
    "mount": "Стальная подставка",
    "description": "Уругвайский аметист — особо насыщенный цвет кристаллов.",
    "href": "../16_product_promos/exhibit.html?id=0254-amethyst-druse35"
  },
  {
    "id": "R–0236",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Морские лилии",
    "period": "Триас",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Морская лилия",
    "latin": "Traumatocrinus guanlingensis",
    "meta": "Крона и малые кроны, Китай, триас<br>Под заказ",
    "price": "Цена по запросу",
    "img": "ph_crinoid_floats",
    "priceValue": null,
    "slug": "0236-crinoid-floats",
    "age": "≈ 235 млн лет, триас",
    "location": "Юньнань-Гуйчжоу, Китай",
    "size": "По запросу",
    "mount": "Деревянная рама",
    "status": "Под заказ",
    "description": "Взрослая крона и рядом — малые кроны той же колонии, редкий групповой сюжет.",
    "href": "../16_product_promos/exhibit.html?id=0236-crinoid-floats"
  },
  {
    "id": "R–0607",
    "world": "grand",
    "worldLabel": "Монументы",
    "category": "Мамонтовая фауна",
    "period": "Плейстоцен",
    "era": "Кайнозой",
    "region": "Россия",
    "name": "Пара бивней мамонта",
    "latin": "Mammuthus primigenius",
    "meta": "Якутия, Россия, 10–40 тыс лет<br>250 см, общий вес пары 74 кг",
    "price": "Цена по запросу",
    "img": "ph_mammoth_tusks",
    "priceValue": null,
    "slug": "0607-mammuthus-primigenius",
    "age": "10–40 тыс лет, поздний плейстоцен",
    "location": "Якутия, Россия",
    "size": "Длина по наружной дуге 250 см, общий вес пары 74 кг",
    "mount": "Деревянные постаменты с резными люльками",
    "description": "Симметричная пара бивней шерстистого мамонта из якутской мерзлоты — редкий случай: два бивня, сохранившие природную патину и глубокий изгиб. Монтируются на парных подставках как единая скульптурная композиция.",
    "href": "../16_product_promos/mammoth-tusks.html"
  },
  {
    "id": "R–0274",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Аммониты",
    "period": "Мел",
    "era": "Мезозой",
    "region": "Россия",
    "latin": "Speetoniceras versicolor",
    "name": "Аммонит Speetoniceras",
    "meta": "Поволжье<br>Бронзовая ребристая раковина",
    "price": "Цена по запросу",
    "img": "ph_speetoniceras",
    "priceValue": null,
    "slug": "0274-speetoniceras",
    "age": "меловой период",
    "location": "Поволжье, Россия",
    "size": "По запросу",
    "mount": "Стальная подставка",
    "description": "Раковина Speetoniceras versicolor бронзового цвета с равномерными поперечными рёбрами — из меловых отложений по берегам Волги.",
    "href": "../16_product_promos/exhibit.html?id=0274-speetoniceras",
    "status": "Под заказ"
  },
  {
    "id": "R–0286",
    "world": "cosmos",
    "worldLabel": "Космос",
    "category": "Метеориты",
    "period": "До зарождения жизни",
    "era": "До зарождения жизни",
    "region": "Россия",
    "latin": "Seymchan Pallasite",
    "name": "Палласит Сеймчан",
    "meta": "Магаданская область, Россия, ≈ 4,56 млрд лет",
    "price": "330 000 ₽",
    "img": "ph_met_seymchan17x25",
    "priceValue": 330000,
    "slug": "0286-seymchan-17x25",
    "age": "≈ 4,56 млрд лет",
    "location": "Магаданская область, Россия",
    "size": "17,5 × 25 см",
    "mount": "Чернёная сталь",
    "description": "Полированный спил палласита Сеймчан: металлическая сетка никелистого железа, в которой сидят зёрна оливина. Вещество родилось на границе ядра и мантии разрушенной протопланеты. Спил 17,5 × 25 см.",
    "href": "../16_product_promos/exhibit.html?id=0286-seymchan-17x25"
  },
  {
    "id": "R–0214",
    "href": "../16_product_promos/exhibit.html?id=0214-anchiornis-huxleyi",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Динозавры",
    "period": "Юра",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Скелет пернатого динозавра",
    "latin": "Anchiornis huxleyi",
    "meta": "Ляонин, Китай, ≈ 160 млн лет<br>Плита 53,5 × 43 см",
    "price": "7 500 000 ₽",
    "img": "ph_anchiornis",
    "priceValue": 7500000,
    "slug": "0214-anchiornis-huxleyi",
    "age": "≈ 160 млн лет, поздняя юра",
    "location": "Провинция Ляонин, Китай, формация Тяоцзишань",
    "size": "Плита 53,5 × 43 см",
    "mount": "Плита известняка с фигурным краем",
    "description": "Anchiornis huxleyi — небольшой пернатый паравийный теропод поздней юры, чьё имя означает «почти птица». Находки этого рода сыграли важную роль в изучении происхождения птиц. Сочленённый скелет на плите с читаемыми зубами и когтями."
  },
  {
    "id": "R–0255",
    "world": "terra",
    "worldLabel": "Земля",
    "category": "Минералы",
    "region": "Россия",
    "latin": "Uvarovite",
    "name": "Уваровит",
    "meta": "Зелёный гранат на постаменте, Пермский край",
    "price": "Цена по запросу",
    "img": "ph_uvarovite",
    "priceValue": null,
    "slug": "0255-uvarovite",
    "location": "Сарановское месторождение, Пермский край, Россия",
    "size": "49 × 30 × 15 см, вес 2,99 кг",
    "mount": "Постамент",
    "description": "Редкий хромовый гранат, названный в честь графа Уварова.",
    "href": "../16_product_promos/exhibit.html?id=0255-uvarovite"
  },
  {
    "id": "R–0237",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Морские лилии",
    "period": "Триас",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Морская лилия",
    "latin": "Traumatocrinus guanlingensis",
    "meta": "Два стебля в раме, Китай, триас<br>Под заказ",
    "price": "Цена по запросу",
    "img": "ph_crinoid_pair",
    "priceValue": null,
    "slug": "0237-crinoid-pair",
    "age": "≈ 235 млн лет, триас",
    "location": "Юньнань-Гуйчжоу, Китай",
    "size": "По запросу",
    "mount": "Деревянная рама",
    "status": "Под заказ",
    "description": "Два стебля уходят параллельно вниз — строгая, почти каллиграфическая плита.",
    "href": "../16_product_promos/exhibit.html?id=0237-crinoid-pair"
  },
  {
    "id": "R–0608",
    "world": "grand",
    "worldLabel": "Монументы",
    "category": "Мамонтовая фауна",
    "period": "Плейстоцен",
    "era": "Кайнозой",
    "region": "Россия",
    "name": "Череп шерстистого носорога",
    "latin": "Coelodonta antiquitatis",
    "meta": "Якутия, Россия, 50–150 тыс лет<br>130 × 82 × 35 см",
    "price": "2 500 000 ₽",
    "img": "ph_rhino_skull",
    "priceValue": 2500000,
    "slug": "0608-coelodonta-antiquitatis",
    "age": "50–150 тыс лет, четвертичный период",
    "location": "Якутия, Россия",
    "size": "130 × 82 × 35 см",
    "mount": "Постамент дома под вес экспоната",
    "description": "Полный череп шерстистого носорога с сохранёнными рогами и зубным рядом. Coelodonta — символ ледниковой Евразии; черепа, сохранившие оба рога и полный зубной ряд, встречаются редко.",
    "href": "../16_product_promos/rhino-skull.html",
    "qty": "Два экземпляра"
  },
  {
    "id": "R–0273",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Аммониты",
    "period": "Мел",
    "era": "Мезозой",
    "region": "Россия",
    "latin": "Craspedodiscus sp.",
    "name": "Аммонит Craspedodiscus",
    "meta": "Ульяновская область<br>Каштаново-красный, с перламутром",
    "price": "Цена по запросу",
    "img": "ph_craspedodiscus",
    "priceValue": null,
    "slug": "0273-craspedodiscus",
    "age": "меловой период",
    "location": "Ульяновская область, Россия",
    "size": "Диаметр около 30 см",
    "mount": "Стальная подставка",
    "description": "Крупный аммонит рода Craspedodiscus насыщенного каштаново-красного цвета с участками окаменевшего перламутра.",
    "href": "../16_product_promos/exhibit.html?id=0273-craspedodiscus",
    "status": "Под заказ"
  },
  {
    "id": "R–0287",
    "world": "cosmos",
    "worldLabel": "Космос",
    "category": "Метеориты",
    "period": "До зарождения жизни",
    "era": "До зарождения жизни",
    "region": "Россия",
    "latin": "Seymchan Pallasite",
    "name": "Палласит Сеймчан",
    "meta": "Магаданская область, Россия, ≈ 4,56 млрд лет",
    "price": "Цена по запросу",
    "img": "ph_met_seymchan_frame",
    "priceValue": null,
    "slug": "0287-seymchan-framed",
    "age": "≈ 4,56 млрд лет",
    "location": "Магаданская область, Россия",
    "size": "По запросу",
    "mount": "Глубокая рама с тёмным паспарту, к стене",
    "description": "Полированный спил палласита Сеймчан: металлическая сетка никелистого железа, в которой сидят зёрна оливина. Вещество родилось на границе ядра и мантии разрушенной протопланеты. Спил оформлен в глубокую раму с тёмным паспарту — готов к стене.",
    "href": "../16_product_promos/exhibit.html?id=0287-seymchan-framed",
    "qty": "Два экземпляра"
  },
  {
    "id": "R–0215",
    "href": "../16_product_promos/exhibit.html?id=0215-dinosaur-eggs",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Динозавры",
    "period": "Мел",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Яйца динозавра",
    "latin": "Elongatoolithidae",
    "meta": "Ляонин, Китай, ≈ 89 млн лет<br>Два удлинённых яйца на общей породе",
    "price": "385 000 ₽",
    "img": "ph_dino_eggs",
    "priceValue": 385000,
    "slug": "0215-dinosaur-eggs",
    "age": "≈ 89 млн лет, поздний мел",
    "location": "Провинция Ляонин, Китай",
    "size": "Два удлинённых яйца на общей породе",
    "mount": "Кованая подставка",
    "description": "Два удлинённых ископаемых яйца группы Elongatoolithidae на общей породе — форма, характерная для овирапторозавров. Выразительная скорлупа с рельефной текстурой, экспонируется на кованой подставке."
  },
  {
    "id": "R–0256",
    "world": "terra",
    "worldLabel": "Земля",
    "category": "Минералы",
    "region": "Китай",
    "latin": "Stibnite, Sb₂S₃",
    "name": "Антимонит",
    "meta": "Стибнит на постаменте, Китай<br>Под заказ",
    "price": "Цена по запросу",
    "img": "ph_stibnite",
    "priceValue": null,
    "slug": "0256-stibnite",
    "location": "Wuning Mine, Цзянси, Китай",
    "size": "24,5 × 20 × 13 см, вес 2 кг",
    "mount": "Полированное деревянное основание с латунной табличкой",
    "status": "Под заказ",
    "description": "Друза с кристаллом больше 13 сантиметров — впечатляющий размер для антимонита.",
    "href": "../16_product_promos/exhibit.html?id=0256-stibnite"
  },
  {
    "id": "R–0238",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Морские лилии",
    "period": "Триас",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Морская лилия",
    "latin": "Traumatocrinus guanlingensis",
    "meta": "Изогнутый стебель в раме, Китай, триас<br>Под заказ",
    "price": "Цена по запросу",
    "img": "ph_crinoid_arc",
    "priceValue": null,
    "slug": "0238-crinoid-arc",
    "age": "≈ 235 млн лет, триас",
    "location": "Юньнань-Гуйчжоу, Китай",
    "size": "По запросу",
    "mount": "Деревянная рама",
    "status": "Под заказ",
    "description": "Стебель входит в кадр дугой из угла — динамичная композиция для кабинета.",
    "href": "../16_product_promos/exhibit.html?id=0238-crinoid-arc"
  },
  {
    "id": "R–0611",
    "href": "../16_product_promos/exhibit.html?id=0611-coelodonta-skeleton",
    "world": "grand",
    "worldLabel": "Монументы",
    "category": "Мамонтовая фауна",
    "period": "Плейстоцен",
    "era": "Кайнозой",
    "region": "Россия",
    "name": "Скелет шерстистого носорога",
    "latin": "Coelodonta antiquitatis",
    "meta": "Якутия, Россия, 50–150 тыс лет<br>Полный скелет",
    "price": "Цена по запросу",
    "img": "ph_rhino_skeleton",
    "priceValue": null,
    "slug": "0611-coelodonta-skeleton",
    "age": "50–150 тыс лет, плейстоцен",
    "location": "Якутия, Россия",
    "size": "Полный скелет",
    "mount": "Профессиональная сборка на скрытом каркасе",
    "description": "Полный смонтированный скелет шерстистого носорога с характерным массивным телосложением и крупными рогами. Обнаружен в Якутии; профессиональная сборка на скрытом стальном каркасе.",
    "status": "Под заказ"
  },
  {
    "id": "R–0211",
    "href": "../16_product_promos/exhibit.html?id=0211-arietites",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Аммониты",
    "period": "Юра",
    "era": "Мезозой",
    "region": "Франция",
    "name": "Аммонит Arietites",
    "latin": "Arietites sp.",
    "meta": "Франция, юрский период<br>Ø 42 см",
    "price": "1 500 000 ₽",
    "img": "ph_arietites",
    "priceValue": 1500000,
    "slug": "0211-arietites",
    "age": "≈ 174 млн лет, юрский период",
    "location": "Франция",
    "size": "Диаметр аммонита 42 см, высота с породой 44 см",
    "mount": "Природная порода как основание",
    "description": "Крупный юрский аммонит рода Arietites с необычным зеленоватым оттенком и ярко выраженными лопастями — сочетание спокойствия и глубины. Диаметр раковины 42 см, высота с породой 44 см."
  },
  {
    "id": "R–0288",
    "world": "cosmos",
    "worldLabel": "Космос",
    "category": "Метеориты",
    "period": "До зарождения жизни",
    "era": "До зарождения жизни",
    "region": "Россия",
    "latin": "Seymchan Pallasite",
    "name": "Сеймчан без оливина",
    "meta": "Магаданская область, Россия, ≈ 4,56 млрд лет",
    "price": "790 000 ₽",
    "img": "ph_met_seymchan_plain",
    "priceValue": 790000,
    "slug": "0288-seymchan-no-olivine",
    "age": "≈ 4,56 млрд лет",
    "location": "Магаданская область, Россия",
    "size": "Вес 1 565 г",
    "mount": "Чернёная сталь",
    "description": "Экземпляр палласита Сеймчан без оливина — почти чистое никелистое железо из той же массы, что и спилы с зелёными зёрнами. Вес 1 565 граммов.",
    "href": "../16_product_promos/exhibit.html?id=0288-seymchan-no-olivine"
  },
  {
    "id": "R–0220",
    "href": "../16_product_promos/exhibit.html?id=0220-spinosaurus-jaw",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Динозавры",
    "period": "Мел",
    "era": "Мезозой",
    "region": "Марокко",
    "name": "Челюсть спинозавра",
    "latin": "Spinosaurus aegyptiacus",
    "meta": "Северная Африка, 100–94 млн лет, сеноман",
    "price": "Цена по запросу",
    "img": "ph_spinosaurus_jaw",
    "priceValue": null,
    "slug": "0220-spinosaurus-jaw",
    "age": "100–94 млн лет, сеноман, поздний мел",
    "location": "Северная Африка",
    "size": "По запросу",
    "mount": "Кованая дугообразная стальная люлька",
    "description": "Фрагмент нижней челюсти Spinosaurus aegyptiacus — крупнейшего хищного теропода Северной Африки. Удлинённые конические зубы почти круглого сечения были приспособлены для удержания скользкой добычи.",
    "status": "Под заказ"
  },
  {
    "id": "R–0257",
    "world": "terra",
    "worldLabel": "Земля",
    "category": "Минералы",
    "region": "Бразилия",
    "latin": "Quartz var. amethyst",
    "name": "Аметист",
    "meta": "Друза на постаменте 51 × 35 × 20 см, Бразилия",
    "price": "Цена по запросу",
    "img": "ph_amethyst_druse51",
    "priceValue": null,
    "slug": "0257-amethyst-druse51",
    "location": "Риу-Гранди-ду-Сул, Бразилия",
    "size": "51 × 35 × 20 см, вес 32,2 кг",
    "mount": "Деревянное основание",
    "description": "Более двухсот кристаллов с золотистыми включениями гётита.",
    "href": "../16_product_promos/exhibit.html?id=0257-amethyst-druse51"
  },
  {
    "id": "R–0239",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Морские лилии",
    "period": "Триас",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Морская лилия",
    "latin": "Traumatocrinus guanlingensis",
    "meta": "Малый веер, Китай, триас<br>Под заказ",
    "price": "Цена по запросу",
    "img": "ph_crinoid_small_fan",
    "priceValue": null,
    "slug": "0239-crinoid-small-fan",
    "age": "≈ 235 млн лет, триас",
    "location": "Юньнань-Гуйчжоу, Китай",
    "size": "По запросу",
    "mount": "Плита на стальной подставке",
    "status": "Под заказ",
    "description": "Камерный экземпляр: небольшой веер, склонённый набок, для настольной подачи.",
    "href": "../16_product_promos/exhibit.html?id=0239-crinoid-small-fan"
  },
  {
    "id": "R–0263",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Мамонтовая фауна",
    "period": "Плейстоцен",
    "era": "Кайнозой",
    "region": "Россия",
    "latin": "Mammuthus primigenius",
    "name": "Нога мамонта",
    "meta": "Мумифицированная, с шерстью, в витрине",
    "price": "Цена по запросу",
    "img": "ph_mammoth_leg",
    "priceValue": null,
    "slug": "0263-mammoth-leg",
    "age": "≈ 2,6 млн – 11 тыс лет, плейстоцен",
    "location": "Россия, зона вечной мерзлоты",
    "size": "По запросу",
    "mount": "Стеклянная витрина на деревянном основании",
    "description": "Мумифицированная нога шерстистого мамонта с сохранившимися мягкими тканями, кожей и рыжей шерстью — в стеклянной витрине на деревянном основании.",
    "href": "../16_product_promos/exhibit.html?id=0263-mammoth-leg",
    "status": "Под заказ"
  },
  {
    "id": "R–0224",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Аммониты",
    "period": "Мезозой",
    "era": "Мезозой",
    "region": "Россия",
    "name": "Аммониты полированные",
    "latin": "Ammonitida",
    "meta": "Россия, мезозой<br>7 предметов",
    "price": "Цена по запросу",
    "img": "ph_ammonite_studio",
    "priceValue": null,
    "slug": "0224-polished-ammonites",
    "age": "252–66 млн лет, мезозой",
    "location": "Россия",
    "size": "Набор из 7 предметов",
    "mount": "Кованые ажурные подставки чёрного металла",
    "description": "Комплект из семи полированных и фигурных аммонитов: срезы с раскрытыми камерами раковины и цельные экземпляры с перламутровой поверхностью. Предметы подбираются поштучно, состав комплекта согласовывается. Съёмка сделана с крупнейшего предмета комплекта.",
    "href": "../16_product_promos/exhibit.html?id=0224-polished-ammonites",
    "status": "Под заказ"
  },
  {
    "id": "R–0289",
    "world": "cosmos",
    "worldLabel": "Космос",
    "category": "Метеориты",
    "period": "До зарождения жизни",
    "era": "До зарождения жизни",
    "region": "Россия",
    "latin": "Omolon Pallasite",
    "name": "Пластина метеорита Омолон",
    "meta": "Бассейн реки Омолон, Магаданская область, Россия, ≈ 4,5 млрд лет",
    "price": "Цена по запросу",
    "img": "ph_met_omolon",
    "priceValue": null,
    "slug": "0289-omolon",
    "age": "≈ 4,5 млрд лет",
    "location": "Бассейн реки Омолон, Магаданская область, Россия",
    "size": "По запросу",
    "mount": "Плавающая рама из чернёной стали, стекло с двух сторон",
    "description": "Пластина палласита Омолон — метеорита весом 250 кг, упавшего 16 мая 1981 года в бассейне реки Омолон в Магаданской области и найденного оленеводом Иваном Тынавьи.",
    "href": "../16_product_promos/exhibit.html?id=0289-omolon",
    "found": "1981 г."
  },
  {
    "id": "R–0221",
    "href": "../16_product_promos/exhibit.html?id=0221-carcharodontosaurus-claw",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Динозавры",
    "period": "Мел",
    "era": "Мезозой",
    "region": "Марокко",
    "name": "Коготь крупного теропода",
    "latin": "Carcharodontosaurus sp.",
    "meta": "Северная Африка, 100–94 млн лет, сеноман<br>≈ 26 см",
    "price": "Цена по запросу",
    "img": "ph_carcharodont_claw",
    "priceValue": null,
    "slug": "0221-carcharodontosaurus-claw",
    "age": "100–94 млн лет, сеноман, поздний мел",
    "location": "Северная Африка",
    "size": "≈ 26 см",
    "mount": "Металлическая подставка",
    "description": "Крупная когтевая фаланга Carcharodontosaurus sp. — одного из крупнейших хищных динозавров сеноманского века. Костная основа рогового чехла: при жизни коготь был длиннее и острее.",
    "status": "Под заказ"
  },
  {
    "id": "R–0258",
    "world": "terra",
    "worldLabel": "Земля",
    "category": "Минералы",
    "region": "Россия",
    "latin": "Quartz, rock crystal",
    "name": "Горный хрусталь",
    "meta": "Друза 47 × 34 × 26 см, Якутия",
    "price": "Цена по запросу",
    "img": "ph_rockcrystal47",
    "priceValue": null,
    "slug": "0258-rockcrystal47",
    "location": "Перекатное месторождение, Якутия, Россия",
    "size": "47 × 34 × 26 см, вес 23 кг",
    "description": "Сотня чётких кристаллов с полностью отработанного месторождения.",
    "href": "../16_product_promos/exhibit.html?id=0258-rockcrystal47"
  },
  {
    "id": "R–0240",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Морские лилии",
    "period": "Триас",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Морская лилия",
    "latin": "Traumatocrinus guanlingensis",
    "meta": "Колония на высокой плите, Китай, триас<br>Под заказ",
    "price": "Цена по запросу",
    "img": "ph_crinoid_colony_tall",
    "priceValue": null,
    "slug": "0240-crinoid-colony-tall",
    "age": "≈ 235 млн лет, триас",
    "location": "Юньнань-Гуйчжоу, Китай",
    "size": "По запросу",
    "mount": "Плита на стальной подставке",
    "status": "Под заказ",
    "description": "Высокая плита с целой колонией — десятки крон на тонких стеблях.",
    "href": "../16_product_promos/exhibit.html?id=0240-crinoid-colony-tall"
  },
  {
    "id": "R–0615",
    "world": "grand",
    "worldLabel": "Монументы",
    "category": "Мамонтовая фауна",
    "period": "Плейстоцен",
    "era": "Кайнозой",
    "region": "Россия",
    "name": "Скелет степного зубра",
    "latin": "Bison priscus",
    "meta": "Россия, 2,5 млн – 10 тыс лет",
    "price": "Цена по запросу",
    "img": "ph_bison_skeleton",
    "priceValue": null,
    "slug": "0615-bison-priscus",
    "age": "2,5 млн – 10 тыс лет назад, плейстоцен",
    "location": "Россия",
    "size": "Рога с размахом более метра, полные размеры по запросу",
    "mount": "Реставрация и монтаж под заказ",
    "description": "Скелет степного зубра Bison priscus — исполина мамонтовой степи. Жил от 2,5 млн до 10 тыс лет назад; самцы достигали двух тонн веса и более двух метров в холке, а размах длинных загнутых вверх рогов превышал метр. Сейчас это подлинный комплект костей: реставрация и музейная сборка выполняются под заказ, поза и подача согласовываются с вами — кадры сборки показывают, каким станет экспонат.",
    "href": "../16_product_promos/exhibit.html?id=0615-bison-priscus",
    "status": "Под заказ"
  },
  {
    "id": "R–0293",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Аммониты",
    "period": "Мел",
    "era": "Мезозой",
    "region": "Мадагаскар",
    "latin": "Cleoniceras sp.",
    "name": "Аммонит Cleoniceras",
    "meta": "Мадагаскар, Меловой период",
    "price": "75 000 ₽",
    "img": "ph_ammo_cleoniceras",
    "priceValue": 75000,
    "slug": "0293-cleoniceras",
    "age": "Меловой период",
    "location": "Мадагаскар",
    "size": "Пара половин",
    "mount": "Чернёная сталь",
    "description": "Пара половин раковины Cleoniceras — рода крупных аммонитов мелового периода. Раковина замещена кальцитом, и на распиле открывается спираль камер с глубоким синим отливом.",
    "href": "../16_product_promos/exhibit.html?id=0293-cleoniceras",
    "qty": "Пара половин"
  },
  {
    "id": "R–0212",
    "href": "../16_product_promos/exhibit.html?id=0212-keichousaurus-hui",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Морские рептилии",
    "period": "Триас",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Скелет кейхозавра",
    "latin": "Keichousaurus hui",
    "meta": "Гуйчжоу, Китай, ≈ 245 млн лет<br>Плита 35,4 × 22,5 см, длина скелета 30,5 см",
    "price": "350 000 ₽",
    "img": "ph_keichousaurus",
    "priceValue": 350000,
    "slug": "0212-keichousaurus-hui",
    "age": "≈ 245 млн лет, триасовый период",
    "location": "Гуйчжоу, Китай",
    "size": "Плита 35,4 × 22,5 см, длина скелета 30,5 см",
    "mount": "Плита породы, вертикальная подача",
    "description": "Keichousaurus hui — небольшой морской завроптеригий с удлинённой шеей, компактным туловищем и конечностями, приспособленными к плаванию. Полный сочленённый скелет на тёмной плите; крупный экземпляр для своего рода."
  },
  {
    "id": "R–0302",
    "world": "cosmos",
    "worldLabel": "Космос",
    "category": "Метеориты",
    "period": "До зарождения жизни",
    "era": "До зарождения жизни",
    "region": "Россия",
    "latin": "Dronino Iron",
    "name": "Композиция из метеоритов Дронино",
    "meta": "Рязанская область, ≈ 4,5 млрд лет",
    "price": "Цена по запросу",
    "img": "ph_dronino_composition",
    "priceValue": null,
    "slug": "0302-dronino-composition",
    "age": "≈ 4,5 млрд лет",
    "location": "Рязанская область, Россия",
    "size": "Семь индивидуалов на общей базе",
    "mount": "Чернёная сталь, единая база со штырями",
    "description": "Семь индивидуалов железного метеорита Дронино разного размера на тонких штырях над единой чернёной базой. Каждый камень — самостоятельный метеорит со своей «дикой» формой; вместе они выстроены в спокойный ритм, задуманный как центрпис длинного стола.",
    "href": "../16_product_promos/exhibit.html?id=0302-dronino-composition",
    "found": "2000 г.",
    "status": "Под заказ"
  },
  {
    "id": "R–0222",
    "href": "../16_product_promos/exhibit.html?id=0222-pterosaur-plate",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Динозавры",
    "period": "Мел",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Скелет птерозавра на плите",
    "latin": "Pterosauria indet.",
    "meta": "Ляонин, Китай, ≈ 125 млн лет<br>Сочленённый скелет на каменной плите",
    "price": "Цена по запросу",
    "img": "ph_pterosaur",
    "priceValue": null,
    "slug": "0222-pterosaur-plate",
    "age": "≈ 125 млн лет, ранний мел",
    "location": "Провинция Ляонин, Китай",
    "size": "Сочленённый скелет на каменной плите",
    "mount": "Настенный или напольный монтаж плиты",
    "description": "Сочленённый ископаемый скелет летающего ящера: вытянутый зубастый череп, лёгкий осевой скелет и сильно удлинённый четвёртый палец, поддерживавший крыло. Требует экспертизы для точной атрибуции.",
    "status": "Под заказ"
  },
  {
    "id": "R–0259",
    "world": "terra",
    "worldLabel": "Земля",
    "category": "Минералы",
    "region": "Китай",
    "latin": "Sphalerite var. marmatite",
    "name": "Сфалерит с кальцитом",
    "meta": "Марматит на постаменте, Китай",
    "price": "Цена по запросу",
    "img": "ph_sphalerite",
    "priceValue": null,
    "slug": "0259-sphalerite",
    "location": "Shuikoushan Mine, Хунань, Китай",
    "size": "29 × 25 × 12 см, вес 5,6 кг",
    "mount": "Чёрное резное основание",
    "description": "Марматит — железистая разновидность сфалерита с почти металлическим блеском.",
    "href": "../16_product_promos/exhibit.html?id=0259-sphalerite",
    "status": "Под заказ"
  },
  {
    "id": "R–0241",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Морские лилии",
    "period": "Триас",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Морская лилия",
    "latin": "Traumatocrinus guanlingensis",
    "meta": "Колония, Китай, триас<br>Под заказ",
    "price": "Цена по запросу",
    "img": "ph_crinoid_colony",
    "priceValue": null,
    "slug": "0241-crinoid-colony",
    "age": "≈ 235 млн лет, триас",
    "location": "Юньнань-Гуйчжоу, Китай",
    "size": "По запросу",
    "mount": "Плита на стальной подставке",
    "status": "Под заказ",
    "description": "Колония, расходящаяся из одного узла, — сцена дрейфа, застывшая целиком.",
    "href": "../16_product_promos/exhibit.html?id=0241-crinoid-colony"
  },
  {
    "id": "R–0616",
    "world": "grand",
    "worldLabel": "Монументы",
    "category": "Мамонтовая фауна",
    "period": "Плейстоцен",
    "era": "Кайнозой",
    "region": "Россия",
    "name": "Скелет плейстоценового волка",
    "latin": "Canis lupus",
    "meta": "Россия, плейстоцен",
    "price": "Цена по запросу",
    "img": "ph_pleistocene_wolf",
    "priceValue": null,
    "slug": "0616-pleistocene-wolf",
    "age": "2,6 млн – 11 тыс лет, плейстоцен",
    "location": "Россия",
    "size": "По запросу",
    "mount": "Низкий подиум",
    "description": "Скелет плейстоценового волка — хищника ледниковой Евразии, современника мамонта и шерстистого носорога. Собран для постоянного экспонирования в тематической коллекции ледникового периода.",
    "href": "../16_product_promos/exhibit.html?id=0616-pleistocene-wolf",
    "status": "Под заказ"
  },
  {
    "id": "R–0294",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Аммониты",
    "period": "Юра",
    "era": "Мезозой",
    "region": "По запросу",
    "latin": "Ammonitida",
    "name": "Аммонит юрский",
    "meta": "По запросу, ≈ 174 млн лет, юрский период",
    "price": "Цена по запросу",
    "img": "ph_ammo_jurassic_polished",
    "priceValue": null,
    "slug": "0294-jurassic-ammonite",
    "age": "≈ 174 млн лет, юрский период",
    "location": "По запросу",
    "size": "По запросу",
    "mount": "Чернёная сталь",
    "description": "Полированная раковина юрского аммонита медово-серых тонов: спираль открыта, видно чередование оборотов и линии роста.",
    "href": "../16_product_promos/exhibit.html?id=0294-jurassic-ammonite"
  },
  {
    "id": "R–0218",
    "href": "../16_product_promos/exhibit.html?id=0218-mixosaurus-plate",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Морские рептилии",
    "period": "Триас",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Скелет ихтиозавра",
    "latin": "Mixosaurus",
    "meta": "Гуйчжоу, Китай, 242–247 млн лет<br>Плита 58 × 30 см, животное 85 см",
    "price": "Цена по запросу",
    "img": "ph_ichthyosaur_plate",
    "priceValue": null,
    "slug": "0218-mixosaurus-plate",
    "age": "242–247 млн лет, триасовый период",
    "location": "Гуйчжоу, Китай",
    "size": "Плита 58 × 30 см, животное 85 см",
    "mount": "Плита породы, горизонтальная подача",
    "description": "Окаменевший скелет ихтиозавра Mixosaurus, прекрасно сохранившийся в плите из тонкозернистого известняка: череп, позвоночник и элементы грудной клетки в анатомической связи. Редкая и ценная палеонтологическая находка.",
    "status": "Под заказ"
  },
  {
    "id": "R–0264",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Бабочки",
    "region": "—",
    "latin": "Papilionidae",
    "name": "Коллекция бабочек",
    "meta": "14 видов · тёмная палитра",
    "price": "Цена по запросу",
    "img": "ph_butterflies_dark",
    "priceValue": null,
    "slug": "0264-butterflies-dark",
    "size": "По запросу",
    "mount": "Рама под стеклом",
    "description": "Кабинетная коллекция из четырнадцати тропических бабочек.",
    "href": "../16_product_promos/exhibit.html?id=0264-butterflies-dark"
  },
  {
    "id": "R–0303",
    "world": "cosmos",
    "worldLabel": "Космос",
    "category": "Метеориты",
    "period": "До зарождения жизни",
    "era": "До зарождения жизни",
    "region": "Россия",
    "latin": "Chelyabinsk LL5",
    "name": "Метеорит Челябинск",
    "meta": "Челябинская область, падение 2013 г.",
    "price": "Цена по запросу",
    "img": "ph_chelyabinsk1",
    "priceValue": null,
    "slug": "0303-chelyabinsk-1",
    "age": "≈ 4,5 млрд лет",
    "location": "Челябинская область, Россия",
    "size": "70 × 55 × 30 мм, вес 119 г",
    "mount": "Чернёная сталь, кольцевая подставка",
    "description": "Осколок Челябинского метеорита — уплощённый овальный индивидуал в гладкой окатанной коре плавления, с характерным выступом на одном конце. Кора застыла за секунды огненного полёта 15 февраля 2013 года.",
    "href": "../16_product_promos/exhibit.html?id=0303-chelyabinsk-1",
    "found": "2013 г."
  },
  {
    "id": "R–0223",
    "href": "../16_product_promos/exhibit.html?id=0223-afrovenator-model",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Динозавры",
    "period": "Юра",
    "era": "Мезозой",
    "region": "Нигер",
    "name": "Модель черепа Afrovenator",
    "latin": "Afrovenator abakensis",
    "meta": "Агадес, Нигер, прообраз 167–161 млн лет<br>Модель черепа ≈ 80–90 см",
    "price": "Цена по запросу",
    "img": "ph_afrovenator",
    "priceValue": null,
    "slug": "0223-afrovenator-model",
    "age": "прообраз 167–161 млн лет, средняя–поздняя юра",
    "location": "Прообраз — Агадес, Нигер, авторская модель",
    "size": "Полноразмерная модель черепа ≈ 80–90 см",
    "mount": "Стальной штырь на чернёном основании",
    "description": "Полноразмерная реконструкция черепа хищного теропода Afrovenator abakensis — «африканского охотника» из формации Тиурарен. Авторская модель по эталонному экземпляру вида; череп воспроизведён в натуральную величину.",
    "status": "Под заказ"
  },
  {
    "id": "R–0260",
    "world": "terra",
    "worldLabel": "Земля",
    "category": "Минералы",
    "region": "ДР Конго",
    "latin": "Malachite",
    "name": "Малахит",
    "meta": "Натёчный, на постаменте, ДР Конго",
    "price": "Цена по запросу",
    "img": "ph_malachite_congo",
    "priceValue": null,
    "slug": "0260-malachite-congo",
    "location": "Haut-Katanga, ДР Конго",
    "size": "42,5 × 24 × 9,7 см, вес 5,35 кг",
    "mount": "Стальные опоры",
    "description": "Крупный натёчный малахит из «геологической сенсации» Катанги.",
    "href": "../16_product_promos/exhibit.html?id=0260-malachite-congo"
  },
  {
    "id": "R–0242",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Морские лилии",
    "period": "Триас",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Морская лилия",
    "latin": "Traumatocrinus guanlingensis",
    "meta": "Группа крон, Китай, триас<br>Под заказ",
    "price": "Цена по запросу",
    "img": "ph_crinoid_group",
    "priceValue": null,
    "slug": "0242-crinoid-group",
    "age": "≈ 235 млн лет, триас",
    "location": "Юньнань-Гуйчжоу, Китай",
    "size": "По запросу",
    "mount": "Плита на стальной подставке",
    "status": "Под заказ",
    "description": "Группа крон на плите свободной формы — самый скульптурный экземпляр.",
    "href": "../16_product_promos/exhibit.html?id=0242-crinoid-group"
  },
  {
    "id": "R–0617",
    "world": "grand",
    "worldLabel": "Монументы",
    "category": "Мамонтовая фауна",
    "period": "Плейстоцен",
    "era": "Кайнозой",
    "region": "Россия",
    "name": "Скелет мамонта",
    "latin": "Mammuthus primigenius",
    "meta": "Якутия, Россия, плейстоцен",
    "price": "Цена по запросу",
    "img": "ph_mammoth_skeleton",
    "priceValue": null,
    "slug": "0617-mammoth-skeleton",
    "age": "2,6 млн – 11 тыс лет, плейстоцен",
    "location": "Якутия, Россия",
    "size": "По запросу",
    "mount": "Скрытый стальной каркас, монтаж на месте",
    "description": "Полный скелет шерстистого мамонта — самый крупный смонтированный экспонат коллекции: задаёт масштаб всему помещению. Монтаж на скрытом стальном каркасе, установка командой дома.",
    "href": "../16_product_promos/exhibit.html?id=0617-mammoth-skeleton",
    "status": "Под заказ"
  },
  {
    "id": "R–0298",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Аммониты",
    "period": "Мел",
    "era": "Мезозой",
    "region": "Россия",
    "latin": "Speetoniceras versicolor",
    "name": "Аммонит Speetoniceras",
    "meta": "Поволжье, ранний мел",
    "price": "200 000 ₽",
    "img": "ph_ammo_speet_small",
    "priceValue": 200000,
    "slug": "0298-speetoniceras-small",
    "age": "Ранний мел",
    "location": "Поволжье, Россия",
    "size": "20 см",
    "mount": "Чернёная сталь",
    "description": "Раковина Speetoniceras около двадцати сантиметров в поперечнике: крупные регулярные рёбра идут через весь оборот. Часть внешнего оборота утрачена — видно устройство камер.",
    "href": "../16_product_promos/exhibit.html?id=0298-speetoniceras-small"
  },
  {
    "id": "R–0230",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Морские рептилии",
    "period": "Триас",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Скелет нотозавра на плите",
    "latin": "Nothosaurus sp.",
    "meta": "Китай, ≈ 240 млн лет<br>Плита 151,5 × 58 см",
    "price": "Цена по запросу",
    "img": "ph_nothosaurus",
    "priceValue": null,
    "status": "Под заказ",
    "slug": "0230-nothosaurus",
    "age": "≈ 240 млн лет, средний триас",
    "location": "Китай",
    "size": "Плита 58 × 151,5 × 4 см, вес 140 кг",
    "mount": "Плита на стальном настенном креплении",
    "description": "Морская рептилия триаса на цельной сланцевой плите: скелет от вытянутого зубастого черепа до длинного хвоста лежит рельефом в камне, кость глубокого чёрного тона контрастирует с серой породой. Единственный объект коллекции, поставляемый под заказ.",
    "href": "../16_product_promos/exhibit.html?id=0230-nothosaurus"
  },
  {
    "id": "R–0265",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Бабочки",
    "region": "—",
    "latin": "Papilionidae",
    "name": "Коллекция бабочек",
    "meta": "14 видов · бирюзовая палитра",
    "price": "Цена по запросу",
    "img": "ph_butterflies_blue",
    "priceValue": null,
    "slug": "0265-butterflies-blue",
    "size": "По запросу",
    "mount": "Рама под стеклом",
    "description": "Кабинетная коллекция из четырнадцати тропических бабочек.",
    "href": "../16_product_promos/exhibit.html?id=0265-butterflies-blue"
  },
  {
    "id": "R–0266",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Змеи",
    "region": "—",
    "latin": "Serpentes",
    "name": "Скелет змеи",
    "meta": "В раме, чёрный бархат",
    "price": "Цена по запросу",
    "img": "ph_snake_portrait",
    "priceValue": null,
    "slug": "0266-snake-portrait",
    "size": "По запросу",
    "mount": "Рама под стеклом",
    "description": "Смонтированный скелет змеи волной на чёрном фоне.",
    "href": "../16_product_promos/exhibit.html?id=0266-snake-portrait"
  },
  {
    "id": "R–0304",
    "world": "cosmos",
    "worldLabel": "Космос",
    "category": "Метеориты",
    "period": "До зарождения жизни",
    "era": "До зарождения жизни",
    "region": "Россия",
    "latin": "Chelyabinsk LL5",
    "name": "Метеорит Челябинск",
    "meta": "Челябинская область, падение 2013 г.",
    "price": "Цена по запросу",
    "img": "ph_chelyabinsk2",
    "priceValue": null,
    "slug": "0304-chelyabinsk-2",
    "age": "≈ 4,5 млрд лет",
    "location": "Челябинская область, Россия",
    "size": "75 × 40 × 45 мм, вес 189 г",
    "mount": "Чернёная сталь, кольцевая подставка",
    "description": "Осколок Челябинского метеорита щитовидной формы: гладкая тёмная кора плавления с маленьким светлым сколом по нижней кромке. Форма набрана за секунды огненного полёта 15 февраля 2013 года.",
    "href": "../16_product_promos/exhibit.html?id=0304-chelyabinsk-2",
    "found": "2013 г."
  },
  {
    "id": "R–0291",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Динозавры",
    "period": "Мел",
    "era": "Мезозой",
    "region": "Китай",
    "latin": "Psittacosaurus sp.",
    "name": "Лапа пситтакозавра",
    "meta": "Провинция Ляонин, Китай, ≈ 125 млн лет, ранний мел",
    "price": "400 000 ₽",
    "img": "ph_psit_paw",
    "priceValue": 400000,
    "slug": "0291-psittacosaurus-foot",
    "age": "≈ 125 млн лет, ранний мел",
    "location": "Провинция Ляонин, Китай",
    "size": "По запросу",
    "mount": "Чернёная сталь",
    "description": "Задняя лапа пситтакозавра в породе: кости голени и пальцы с когтями лежат так, как их застало захоронение. Ранний мел, леса на территории нынешней провинции Ляонин.",
    "href": "../16_product_promos/exhibit.html?id=0291-psittacosaurus-foot"
  },
  {
    "id": "R–0261",
    "world": "terra",
    "worldLabel": "Земля",
    "category": "Минералы",
    "region": "Россия",
    "latin": "Quartz, rock crystal",
    "name": "Горный хрусталь",
    "meta": "Друза 50 × 36 × 23 см, Якутия",
    "price": "Цена по запросу",
    "img": "ph_rockcrystal50",
    "priceValue": null,
    "slug": "0261-rockcrystal50",
    "location": "Перекатное месторождение, Якутия, Россия",
    "size": "50 × 36 × 23 см, вес 31,5 кг",
    "mount": "Деревянное основание",
    "description": "Сотня кристаллов, выстроенных в одном направлении.",
    "href": "../16_product_promos/exhibit.html?id=0261-rockcrystal50"
  },
  {
    "id": "R–0243",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Морские лилии",
    "period": "Триас",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Морская лилия",
    "latin": "Traumatocrinus guanlingensis",
    "meta": "Скопление, Китай, триас<br>Под заказ",
    "price": "Цена по запросу",
    "img": "ph_crinoid_cluster",
    "priceValue": null,
    "slug": "0243-crinoid-cluster",
    "age": "≈ 235 млн лет, триас",
    "location": "Юньнань-Гуйчжоу, Китай",
    "size": "По запросу",
    "mount": "Плита на стальной подставке",
    "status": "Под заказ",
    "description": "Плотное переплетение крон и стеблей — фактура, которую хочется разглядывать.",
    "href": "../16_product_promos/exhibit.html?id=0243-crinoid-cluster"
  },
  {
    "id": "R–0253",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Мамонтовая фауна",
    "period": "Плейстоцен",
    "era": "Кайнозой",
    "region": "Россия",
    "latin": "Ursus spelaeus",
    "name": "Передняя лапа пещерного медведя",
    "meta": "Башкирия, ≈ 10–12 тыс. лет",
    "price": "200 000 ₽",
    "img": "ph_cavebear_paw_front",
    "priceValue": 200000,
    "slug": "0253-cavebear-paw-front",
    "age": "≈ 10–12 тыс. лет, плейстоцен",
    "location": "Башкортостан, Россия",
    "size": "25,5 × 19,5 × 9,5 см; вес 600 г",
    "mount": "Металлический каркас на подставке",
    "description": "Передняя лапа хищника, превосходившего размером современных медведей: кости в анатомической связи, монтаж на металлическом каркасе.",
    "href": "../16_product_promos/exhibit.html?id=0253-cavebear-paw-front"
  },
  {
    "id": "R–0299",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Аммониты",
    "period": "Юра",
    "era": "Мезозой",
    "region": "По запросу",
    "latin": "Ammonitida",
    "name": "Аммонит в породе",
    "meta": "Юрский период, ≈ 174 млн лет",
    "price": "Цена по запросу",
    "img": "ph_ammo_jurassic_block",
    "priceValue": null,
    "slug": "0299-jurassic-ammonite-block",
    "age": "≈ 174 млн лет, юрский период",
    "location": "По запросу",
    "size": "По запросу",
    "mount": "Чернёная сталь",
    "description": "Юрский аммонит, оставленный в породе: раковина занимает почти весь блок, а известняк вокруг не тронут инструментом. Видно и саму спираль, и то, как она лежала в осадке.",
    "href": "../16_product_promos/exhibit.html?id=0299-jurassic-ammonite-block"
  },
  {
    "id": "R–0292",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Морские рептилии",
    "period": "Триас",
    "era": "Мезозой",
    "region": "Китай",
    "latin": "Keichousaurus hui",
    "name": "Скелет кейхозавра",
    "meta": "Гуйчжоу, Китай, ≈ 245 млн лет, триасовый период",
    "price": "900 000 ₽",
    "img": "ph_keicho_pink",
    "priceValue": 900000,
    "slug": "0292-keichousaurus-slab",
    "age": "≈ 245 млн лет, триасовый период",
    "location": "Гуйчжоу, Китай",
    "size": "По запросу",
    "mount": "Чернёная сталь",
    "description": "Скелет кейхозавра на плите светлого известняка: длинная шея, небольшой череп, конечности-вёсла и длинный хвост. Сочленение сохранено — животное лежит так, как опустилось на дно триасового моря.",
    "href": "../16_product_promos/exhibit.html?id=0292-keichousaurus-slab"
  },
  {
    "id": "R–0267",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Бабочки",
    "region": "—",
    "latin": "Papilionidae · Nymphalidae",
    "name": "Коллекция бабочек",
    "meta": "14 видов · янтарная палитра",
    "price": "Цена по запросу",
    "img": "ph_butterflies_amber",
    "priceValue": null,
    "slug": "0267-butterflies-amber",
    "size": "По запросу",
    "mount": "Рама под стеклом",
    "description": "Кабинетная коллекция из четырнадцати тропических бабочек.",
    "href": "../16_product_promos/exhibit.html?id=0267-butterflies-amber"
  },
  {
    "id": "R–0268",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Змеи",
    "region": "—",
    "latin": "Serpentes",
    "name": "Скелет змеи",
    "meta": "Крупная волна, чёрная рама",
    "price": "Цена по запросу",
    "img": "ph_snake_large",
    "priceValue": null,
    "slug": "0268-snake-large",
    "size": "По запросу",
    "mount": "Рама под стеклом",
    "description": "Крупный смонтированный скелет змеи широкими кольцами.",
    "href": "../16_product_promos/exhibit.html?id=0268-snake-large"
  },
  {
    "id": "R–0209",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Ископаемые рыбы",
    "period": "Девон",
    "era": "Палеозой",
    "region": "—",
    "name": "Панцирная рыба Bothriolepis",
    "latin": "Bothriolepis sp.",
    "meta": "≈ 350 млн лет<br>50 см",
    "price": "3 500 000 ₽",
    "img": "ph_bothriolepis",
    "priceValue": 3500000,
    "slug": "0209-bothriolepis-sp",
    "age": "≈ 350 млн лет, девон",
    "location": "",
    "size": "50 см",
    "mount": "Стальной штырь на прямоугольном основании",
    "description": "Панцирная рыба девона — одно из первых существ, «одевших» тело в костяную броню. Плита с рельефным отпечатком; готовится авторская подставка.",
    "href": "../16_product_promos/bothriolepis.html"
  },
  {
    "id": "R–0229",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Пещерные львы",
    "period": "Плейстоцен",
    "era": "Кайнозой",
    "region": "Евразия",
    "name": "Череп пещерного льва",
    "latin": "Panthera leo spelaea",
    "meta": "Евразия, плейстоцен<br>40 × 30 × 28 см",
    "price": "Цена по запросу",
    "img": "ph_cave_lion_vitrine",
    "priceValue": null,
    "slug": "0229-cave-lion-skull-vitrine",
    "age": "2,6 млн – 11 тыс лет, плейстоцен",
    "location": "Евразия",
    "size": "40 × 30 × 28 см",
    "mount": "Стеклянная витрина на чёрном основании, опора из чернёной стали",
    "description": "Полный череп пещерного льва с нижней челюстью, смонтированный в раскрытой позе на стальной опоре. Кость минерализована до тёплого бурого тона, сохранены оба верхних и оба нижних клыка и зубной ряд. Объект поставляется в собственной стеклянной витрине на чёрном основании — его не нужно ничем дополнять.",
    "href": "../16_product_promos/exhibit.html?id=0229-cave-lion-skull-vitrine",
    "hidden": true,
    "status": "Под заказ"
  },
  {
    "id": "R–0201",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Мегалодон",
    "period": "Неоген",
    "era": "Кайнозой",
    "region": "Индонезия",
    "name": "Зуб мегалодона",
    "latin": "Otodus megalodon",
    "meta": "Индонезия, ≈ 23 млн лет<br>Высота 14,5 см",
    "price": "400 000 ₽",
    "img": "ph_megalodon",
    "href": "../16_product_promos/megalodon-tooth.html",
    "priceValue": 400000,
    "slug": "megalodon-tooth",
    "age": "≈ 23 млн лет, миоцен",
    "location": "Индонезия",
    "size": "Высота 14,5 см",
    "mount": "Стальной стенд",
    "description": "Зуб крупнейшего хищника в истории океана, поднятый дайверами с глубины. Эмаль сохранилась целиком, режущая кромка не сточена и не подправлена.",
    "qty": "Два экземпляра"
  },
  {
    "id": "R–0217",
    "href": "../16_product_promos/exhibit.html?id=0217-dikelokephalina",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Трилобиты",
    "period": "Ордовик",
    "era": "Палеозой",
    "region": "Марокко",
    "name": "Гигантский трилобит",
    "latin": "Dikelokephalina brenchleyi",
    "meta": "Загора, Марокко, ≈ 480–472 млн лет<br>Плита 52,5 × 36,5 см, тело 33,5 × 27 см",
    "price": "950 000 ₽",
    "img": "ph_trilobite_giant",
    "priceValue": 950000,
    "slug": "0217-dikelokephalina",
    "age": "≈ 480–472 млн лет, ранний ордовик",
    "location": "Загора, Марокко, формация Fezouata",
    "size": "Плита 52,5 × 36,5 см, тело 33,5 × 27 см",
    "mount": "Порода с необработанными краями",
    "description": "Dikelokephalina — род крупных морских трилобитов древней Гондваны. Экземпляр из сланцев Fezouata достигает редкой для трилобитов величины: тело более тридцати сантиметров, глубокий рельеф сегментов на контрастной тёмной плите."
  },
  {
    "id": "R–0305",
    "world": "cosmos",
    "worldLabel": "Космос",
    "category": "Метеориты",
    "period": "До зарождения жизни",
    "era": "До зарождения жизни",
    "region": "Россия",
    "latin": "Chelyabinsk LL5",
    "name": "Метеорит Челябинск",
    "meta": "Челябинская область, падение 2013 г.",
    "price": "Цена по запросу",
    "img": "ph_chelyabinsk3",
    "priceValue": null,
    "slug": "0305-chelyabinsk-3",
    "age": "≈ 4,5 млрд лет",
    "location": "Челябинская область, Россия",
    "size": "43 × 38 × 24 мм, вес 42 г",
    "mount": "Чернёная сталь, кольцевая подставка",
    "description": "Осколок Челябинского метеорита со сколом: чёрная кора плавления разорвана, и в разломе видна светло-серая хондритовая матрица с блёстками металла — редкий случай, когда камень показывает и «рубашку», и нутро.",
    "href": "../16_product_promos/exhibit.html?id=0305-chelyabinsk-3",
    "found": "2013 г."
  },
  {
    "id": "R–0297",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Динозавры",
    "period": "Мел",
    "era": "Мезозой",
    "region": "Марокко",
    "latin": "Spinosaurus aegyptiacus",
    "name": "Зуб спинозавра в раме",
    "meta": "Марокко, ≈ 112–93 млн лет, меловой период",
    "price": "Цена по запросу",
    "img": "ph_tooth_spinosaurus",
    "priceValue": null,
    "slug": "0297-spinosaurus-tooth",
    "age": "≈ 112–93 млн лет, меловой период",
    "location": "Марокко",
    "size": "По запросу",
    "mount": "Глубокая рама",
    "description": "Зуб спинозавра, оформленный в глубокую раму: длинный конус эмали с тонкими вертикальными рёбрами — форма, приспособленная удерживать рыбу.",
    "href": "../16_product_promos/exhibit.html?id=0297-spinosaurus-tooth",
    "qty": "Два экземпляра"
  },
  {
    "id": "R–0262",
    "world": "terra",
    "worldLabel": "Земля",
    "category": "Минералы",
    "region": "Россия",
    "latin": "Septarian nodule",
    "name": "Септария",
    "meta": "Полированный срез 72 × 65 см, Поволжье",
    "price": "Цена по запросу",
    "img": "ph_septaria",
    "priceValue": null,
    "slug": "0262-septaria",
    "location": "Ульяновская область, Россия",
    "size": "72 × 65 × 4 см, вес 36,3 кг",
    "mount": "Стальная подставка",
    "description": "Огромная септария с перегородками из симбирцита.",
    "href": "../16_product_promos/exhibit.html?id=0262-septaria"
  },
  {
    "id": "R–0244",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Морские лилии",
    "period": "Триас",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Морская лилия",
    "latin": "Traumatocrinus guanlingensis",
    "meta": "Три кроны, Китай, триас<br>Под заказ",
    "price": "Цена по запросу",
    "img": "ph_crinoid_trio",
    "priceValue": null,
    "slug": "0244-crinoid-trio",
    "age": "≈ 235 млн лет, триас",
    "location": "Юньнань-Гуйчжоу, Китай",
    "size": "По запросу",
    "mount": "Плита на стальной подставке",
    "status": "Под заказ",
    "description": "Три кроны в одном кадре камня — ритмичная вертикальная плита.",
    "href": "../16_product_promos/exhibit.html?id=0244-crinoid-trio"
  },
  {
    "id": "R–0275",
    "world": "grand",
    "worldLabel": "Монументы",
    "category": "Мамонтовая фауна",
    "period": "Плейстоцен",
    "era": "Кайнозой",
    "region": "Россия",
    "latin": "Ursus spelaeus",
    "name": "Череп пещерного медведя",
    "meta": "Якутия, ≈ 60 000 лет",
    "price": "2 500 000 ₽",
    "img": "ph_cavebear_skull",
    "priceValue": 2500000,
    "slug": "0275-cave-bear-skull",
    "age": "≈ 60 000 лет, поздний плейстоцен",
    "location": "Якутия, Россия",
    "size": "40 × 30 × 28 см",
    "mount": "Чернёная сталь, череп с шейными позвонками",
    "description": "Череп поднят из вечной мерзлоты Якутии с глубины около семидесяти метров — один из самых древних черепов пещерного медведя. Сохранены клыки, зубной ряд и высокий гребень черепной коробки: к нему крепились жевательные мышцы, дававшие хищнику ледниковой Евразии его хватку.",
    "href": "../16_product_promos/exhibit.html?id=0275-cave-bear-skull"
  },
  {
    "id": "R–0300",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Аммониты",
    "period": "Мел",
    "era": "Мезозой",
    "region": "Россия",
    "latin": "Speetoniceras versicolor",
    "name": "Аммонит Speetoniceras",
    "meta": "Поволжье, ранний мел",
    "price": "900 000 ₽",
    "img": "ph_ammo_speet_bronze",
    "priceValue": 900000,
    "slug": "0300-speetoniceras-bronze",
    "age": "Ранний мел",
    "location": "Поволжье, Россия",
    "size": "По запросу",
    "mount": "Чернёная сталь",
    "description": "Крупная раковина Speetoniceras versicolor характерного бронзового оттенка. Толщина раковины плавно нарастает от центра к наружной жилой камере, частые рёбра идут через весь оборот.",
    "href": "../16_product_promos/exhibit.html?id=0300-speetoniceras-bronze"
  },
  {
    "id": "R–0296",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Морские рептилии",
    "period": "Мел",
    "era": "Мезозой",
    "region": "По запросу",
    "latin": "Mosasauridae",
    "name": "Зуб мозазавра",
    "meta": "По запросу, ≈ 135–65 млн лет, меловой период",
    "price": "Цена по запросу",
    "img": "ph_tooth_mosasaur",
    "priceValue": null,
    "slug": "0296-mosasaur-tooth",
    "age": "≈ 135–65 млн лет, меловой период",
    "location": "По запросу",
    "size": "По запросу",
    "mount": "Чернёная сталь",
    "description": "Зуб мозазавра — морской рептилии мелового периода: массивный конус эмали с тонкими вертикальными рёбрами и костным корнем.",
    "href": "../16_product_promos/exhibit.html?id=0296-mosasaur-tooth"
  },
  {
    "id": "R–0269",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Бабочки",
    "region": "—",
    "latin": "Nymphalidae · Papilionidae · Pieridae",
    "name": "Коллекция бабочек",
    "meta": "14 видов · смешанная палитра",
    "price": "Цена по запросу",
    "img": "ph_butterflies_warm",
    "priceValue": null,
    "slug": "0269-butterflies-warm",
    "size": "По запросу",
    "mount": "Рама под стеклом",
    "description": "Кабинетная коллекция из четырнадцати бабочек.",
    "href": "../16_product_promos/exhibit.html?id=0269-butterflies-warm"
  },
  {
    "id": "R–0270",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Змеи",
    "region": "—",
    "latin": "Serpentes",
    "name": "Скелет змеи",
    "meta": "Вытянутая рама, нисходящая волна",
    "price": "Цена по запросу",
    "img": "ph_snake_tall",
    "priceValue": null,
    "slug": "0270-snake-tall",
    "size": "По запросу",
    "mount": "Рама под стеклом",
    "description": "Скелет змеи нисходящей волной в вытянутой раме.",
    "href": "../16_product_promos/exhibit.html?id=0270-snake-tall"
  },
  {
    "id": "R–0219",
    "href": "../16_product_promos/exhibit.html?id=0219-dunkleosteus",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Ископаемые рыбы",
    "period": "Девон",
    "era": "Палеозой",
    "region": "—",
    "name": "Череп Dunkleosteus",
    "latin": "Dunkleosteus terrelli",
    "meta": "≈ 360 млн лет",
    "price": "Цена по запросу",
    "img": "ph_dunkleosteus",
    "priceValue": null,
    "slug": "0219-dunkleosteus",
    "age": "≈ 360 млн лет, поздний девон",
    "location": "Реконструкция по научным данным",
    "size": "По запросу",
    "mount": "Подставка из чернёной стали на штырях",
    "description": "Реконструкция черепа и головного щита крупной панцирной рыбы позднего девона. Массивные костные пластины образовывали защитную броню; вместо зубов — острые режущие костные кромки.",
    "status": "Под заказ"
  },
  {
    "id": "R–0228",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Пещерные львы",
    "period": "Плейстоцен",
    "era": "Кайнозой",
    "region": "Россия",
    "name": "Череп пещерного льва",
    "latin": "Panthera leo spelaea",
    "meta": "Евразия, плейстоцен",
    "price": "Цена по запросу",
    "img": "ph_cave_lion2",
    "priceValue": null,
    "slug": "0228-cave-lion-skull-2",
    "age": "2,6 млн – 11 тыс лет, плейстоцен",
    "location": "Евразия",
    "size": "По запросу",
    "mount": "Подставка из чернёной стали",
    "description": "Кость глубоко минерализована — тон уходит от охры к тёмно-бурому, поверхность держит сеть древних трещин. Сохранены клыки, зубной ряд и высокий гребень черепной коробки; подача фронтальная, на подставке из чернёной стали.",
    "href": "../16_product_promos/exhibit.html?id=0228-cave-lion-skull-2",
    "status": "Под заказ"
  },
  {
    "id": "R–0295",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Мегалодон",
    "period": "Палеоген",
    "era": "Кайнозой",
    "region": "По запросу",
    "latin": "Otodus obliquus",
    "name": "Зуб акулы Otodus obliquus",
    "meta": "По запросу, ≈ 54 млн лет, палеоген",
    "price": "Цена по запросу",
    "img": "ph_tooth_otodus",
    "priceValue": null,
    "slug": "0295-otodus-tooth",
    "age": "≈ 54 млн лет, палеоген",
    "location": "По запросу",
    "size": "По запросу",
    "mount": "Чернёная сталь",
    "description": "Зуб Otodus obliquus — крупной акулы палеогена, предковой линии мегалодона. Широкое треугольное лезвие эмали, светлый корень и боковые зубчики по краям.",
    "href": "../16_product_promos/exhibit.html?id=0295-otodus-tooth"
  },
  {
    "id": "R–0301",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Трилобиты",
    "period": "Палеозой",
    "era": "Палеозой",
    "region": "По запросу",
    "latin": "Trilobita",
    "name": "Плита с трилобитами",
    "meta": "Палеозой, массовое захоронение",
    "price": "Цена по запросу",
    "img": "ph_trilo_plate",
    "priceValue": null,
    "slug": "0301-trilobite-plate",
    "age": "По запросу",
    "location": "По запросу",
    "size": "По запросу",
    "mount": "Чернёная сталь",
    "description": "Несколько десятков целых трилобитов лежат вплотную друг к другу на одной плите — мортальное скопление: животных засыпало разом, одним выбросом осадка, поэтому панцири не разошлись и не окатались. Вид по имеющимся данным не установлен.",
    "href": "../16_product_promos/exhibit.html?id=0301-trilobite-plate"
  },
  {
    "id": "R–0612",
    "world": "grand",
    "worldLabel": "Монументы",
    "category": "Крокодилиформы",
    "period": "Палеоген",
    "era": "Кайнозой",
    "region": "Марокко",
    "latin": "Dyrosaurus sp.",
    "name": "Скелет дирозавра",
    "meta": "Улед-Абдун, Марокко<br>Под заказ",
    "price": "Цена по запросу",
    "img": "ph_dyrosaurus",
    "priceValue": null,
    "status": "Под заказ",
    "slug": "0612-dyrosaurus",
    "age": "≈ 65 млн лет, палеоген",
    "location": "Бассейн Улед-Абдун, Хурибга, Марокко",
    "size": "Около 5–6 м",
    "mount": "Монтаж на стальных опорах (выполняется домом)",
    "description": "Скелет дирозавра — длиннорылого крокодилиформа из фосфоритов Марокко. Экземпляр поставляется под заказ; сборка и монтаж выполняются домом.",
    "href": "../16_product_promos/exhibit.html?id=0612-dyrosaurus"
  },
  {
    "id": "R–0252",
    "world": "terra",
    "worldLabel": "Земля",
    "category": "Жеоды",
    "region": "Бразилия",
    "latin": "Quartz var. amethyst",
    "name": "Аметист",
    "meta": "Жеода 123 см, Бразилия",
    "price": "Цена по запросу",
    "img": "ph_amethyst_geode123",
    "priceValue": null,
    "slug": "0252-amethyst-geode123",
    "location": "Минас-Жерайс, Бразилия",
    "size": "Около 123 × 23 × 22 см, вес 66 кг",
    "description": "Метровая жеода с сотнями кристаллов — кристаллический мир, в котором легко зависнуть надолго.",
    "href": "../16_product_promos/exhibit.html?id=0252-amethyst-geode123"
  },
  {
    "id": "R–0208",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Саблезубые кошки",
    "period": "Неоген",
    "era": "Кайнозой",
    "region": "Китай",
    "name": "Череп саблезубой кошки",
    "latin": "Machairodus sp.",
    "meta": "Ганьсу, Китай, 5,3–11,6 млн лет<br>39 × 23 × 14 см",
    "price": "Цена по запросу",
    "img": "ph_sabertooth",
    "priceValue": null,
    "slug": "0208-machairodus-sp",
    "age": "5,3–11,6 млн лет, неоген",
    "location": "Провинция Ганьсу, Китай",
    "size": "39 × 23 × 14 см",
    "mount": "Подставка из чернёной стали со штырём",
    "description": "Череп одного из крупнейших саблезубых хищников неогена с клинковидными клыками. Экспонируется на музейной стойке — редкий предок «саблезубого тигра».",
    "href": "../16_product_promos/sabertooth-skull.html",
    "status": "Под заказ"
  },
  {
    "id": "R–0245",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Ракоскорпионы",
    "period": "Силур",
    "era": "Палеозой",
    "region": "Украина",
    "latin": "Balteurypterus tetragonophtalmus",
    "name": "Ракоскорпион",
    "meta": "Balteurypterus, силур",
    "price": "1 200 000 ₽",
    "img": "ph_eurypterid",
    "priceValue": 1200000,
    "slug": "0245-eurypterid",
    "age": "≈ 430–420 млн лет, силур",
    "location": "Хмельницкая область, река Смотрич, Украина",
    "size": "Плита около 33 × 28,5 × 4,5 см, вес 3,25 кг",
    "mount": "Стальная подставка",
    "description": "Первые членистоногие, вышедшие из воды на сушу, — родня всем сухопутным членистоногим, включая насекомых.",
    "href": "../16_product_promos/exhibit.html?id=0245-eurypterid"
  },
  {
    "id": "R–0251",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Эдиакарская фауна",
    "period": "Эдиакарий",
    "era": "Докембрий",
    "region": "Украина",
    "latin": "Nemiana simplex",
    "name": "Медузоиды Nemiana",
    "meta": "Эдиакарская фауна, венд",
    "price": "Цена по запросу",
    "img": "ph_nemiana",
    "priceValue": null,
    "slug": "0251-nemiana",
    "age": "≈ 540 млн лет, эдиакарий (венд)",
    "location": "Могилёв-Подольский район, река Днестр, Украина",
    "size": "Плита около 32 × 20,5 × 3 см, вес 2,57 кг",
    "mount": "Стальная подставка",
    "description": "Более 50 отпечатков организмов, живших до кембрийского взрыва.",
    "href": "../16_product_promos/exhibit.html?id=0251-nemiana"
  },
  {
    "id": "R–0226",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Гиены",
    "period": "Неоген",
    "era": "Кайнозой",
    "region": "Азия",
    "name": "Череп динокрокуты",
    "latin": "Dinocrocuta gigantea",
    "meta": "Азия, миоцен",
    "price": "Цена по запросу",
    "img": "ph_hyena_skull",
    "priceValue": null,
    "slug": "0226-hyena-skull",
    "age": "23–5,3 млн лет, миоцен",
    "location": "Азия",
    "size": "По запросу",
    "mount": "Породное основание, постамент под заказ",
    "description": "Череп динокрокуты — гигантского хищника миоцена, обитавшего в Азии и Африке. Внешне похожая на гиену, Dinocrocuta обладала самыми мощными челюстями своего времени: короткая высокая морда и крупные конические зубы дробили кости крупной добычи. Череп этой особи крупнее, чем у пещерного медведя.",
    "href": "../16_product_promos/exhibit.html?id=0226-hyena-skull",
    "status": "Под заказ"
  },
  {
    "id": "R–0290",
    "world": "terra",
    "worldLabel": "Земля",
    "category": "Ископаемая древесина",
    "period": "Юра",
    "era": "Мезозой",
    "region": "По запросу",
    "latin": "Fossil wood",
    "name": "Окаменелое дерево",
    "meta": "По запросу, Юрский период",
    "price": "100 000 ₽",
    "img": "ph_wood_petrified",
    "priceValue": 100000,
    "slug": "0290-petrified-wood",
    "age": "Юрский период",
    "location": "По запросу",
    "size": "По запросу",
    "mount": "Чернёная сталь",
    "description": "Фрагмент древнего дерева, сохранившийся в камне. При фоссилизации органическое вещество древесины постепенно замещалось минеральными соединениями, и первоначальная структура осталась: текстура волокон, годичные кольца, особенности строения.",
    "href": "../16_product_promos/exhibit.html?id=0290-petrified-wood",
    "qty": "Два экземпляра"
  },
  {
    "id": "R–0306",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Мамонтовая фауна",
    "period": "Плейстоцен",
    "era": "Кайнозой",
    "region": "Россия",
    "latin": "Ursus spelaeus",
    "name": "Задняя лапа пещерного медведя",
    "meta": "Башкирия, ≈ 10–12 тыс. лет",
    "price": "200 000 ₽",
    "img": "ph_cavebear_paw_hind",
    "priceValue": 200000,
    "slug": "0306-cavebear-paw-hind",
    "age": "≈ 10–12 тыс. лет, плейстоцен",
    "location": "Башкортостан, Россия",
    "size": "34,5 × 17,7 × 7,4 см; вес 632 г",
    "mount": "Металлический каркас на подставке",
    "description": "Задняя лапа хищника, превосходившего размером современных медведей: массивная пяточная кость, все кости в анатомической связи.",
    "href": "../16_product_promos/exhibit.html?id=0306-cavebear-paw-hind"
  },
  {
    "id": "R–0307",
    "world": "cosmos",
    "worldLabel": "Космос",
    "category": "Метеориты",
    "period": "До зарождения жизни",
    "era": "До зарождения жизни",
    "region": "Китай",
    "latin": "Aletai Iron",
    "name": "Куб из метеорита Алетай",
    "meta": "Алтайские горы, Китай, 1 200 г",
    "price": "360 000 ₽",
    "img": "ph_met_aletai_cube2",
    "priceValue": 360000,
    "slug": "0307-aletai-cube-2",
    "age": "≈ 4,5 млрд лет",
    "location": "Алтайские горы, Китай",
    "size": "Вес 1 200 г",
    "mount": "Чернёная сталь",
    "description": "Куб, вырезанный из фрагмента железного метеорита Алетай и отполированный по всем граням: на каждой видны видманштеттеновы фигуры.",
    "href": "../16_product_promos/exhibit.html?id=0307-aletai-cube-2"
  },
  {
    "id": "R–0308",
    "world": "cosmos",
    "worldLabel": "Космос",
    "category": "Метеориты",
    "period": "До зарождения жизни",
    "era": "До зарождения жизни",
    "region": "Россия",
    "latin": "Kainsaz CO3",
    "name": "Метеорит Каинсаз",
    "meta": "Татарстан, Россия, 423 г",
    "price": "1 692 000 ₽",
    "img": "ph_met_kainsaz_b",
    "priceValue": 1692000,
    "slug": "0308-kainsaz-2",
    "age": "≈ 4,59 млрд лет",
    "location": "Татарстан, Россия",
    "size": "Вес 423 г",
    "mount": "Чернёная сталь",
    "description": "Углистый хондрит — вещество, которое старше Земли примерно на пятьдесят миллионов лет и сохранило органические соединения ранней Солнечной системы.",
    "href": "../16_product_promos/exhibit.html?id=0308-kainsaz-2"
  },
  {
    "id": "R–0309",
    "world": "cosmos",
    "worldLabel": "Космос",
    "category": "Метеориты",
    "period": "До зарождения жизни",
    "era": "До зарождения жизни",
    "region": "Россия",
    "latin": "Ozerki L6",
    "name": "Метеорит Озерки",
    "meta": "Липецкая область, Россия, 141 г",
    "price": "423 000 ₽",
    "img": "ph_met_ozerki_b",
    "priceValue": 423000,
    "slug": "0309-ozerki-2",
    "age": "≈ 4,5 млрд лет",
    "location": "Липецкая область, Россия",
    "size": "Вес 141 г",
    "mount": "Чернёная сталь",
    "description": "Камень собран сразу после падения — поэтому на нём сохранилась первичная кора плавления, тонкая чёрная плёнка, застывшая за секунды прохождения через атмосферу.",
    "href": "../16_product_promos/exhibit.html?id=0309-ozerki-2"
  }
];
