/* RELICTUM — единый источник данных каталога.
   ДОБАВИТЬ ЭКСПОНАТ = добавить один объект сюда (см. 16_product_promos/INTAKE.md).
   Только реальная коллекция (наличие Михаила + лунный метеорит).
   Используется: catalog.html, object.html, главная. */
window.RELICTUM_CATALOG = [
  {
    "id": "R–0101",
    "href": "../16_product_promos/exhibit.html?id=seymchan-pallasite",
    "world": "cosmos",
    "worldLabel": "Космос",
    "category": "Метеориты",
    "period": "До зарождения жизни",
    "era": "До зарождения жизни",
    "region": "Россия",
    "name": "Палласит Сеймчан",
    "latin": "Seymchan Pallasite",
    "meta": "Магаданская область, Россия, ≈ 4,56 млрд лет<br>Срез 18 × 14 см, 1 240 г",
    "price": "2 400 000 ₽",
    "img": "ph_seymchan",
    "priceValue": 2400000,
    "slug": "seymchan-pallasite",
    "age": "≈ 4,56 млрд лет",
    "location": "Магаданская область, Россия",
    "found": "1967 г.",
    "size": "Срез 18 × 14 см, 1 240 г",
    "mount": "Стальная подставка",
    "description": "Полированный срез железно-каменного метеорита с кристаллами оливина, застывшими в никелистом железе. Палласиты — вещество границы ядра и мантии разрушенной протопланеты; старше самой Земли."
  },
  {
    "id": "R–0201",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Мегалодон",
    "period": "Неоген",
    "era": "Кайнозой",
    "region": "Индонезия",
    "name": "Зуб мегалодона",
    "latin": "Otodus megalodon",
    "meta": "Индонезия, ≈ 23 млн лет<br>Высота 14,5 см",
    "price": "1 250 000 ₽",
    "img": "ph_megalodon",
    "href": "../16_product_promos/megalodon-tooth.html",
    "priceValue": 1250000,
    "slug": "megalodon-tooth",
    "age": "≈ 23 млн лет, миоцен",
    "location": "Индонезия",
    "size": "Высота 14,5 см",
    "mount": "Стальной стенд",
    "description": "Зуб крупнейшего хищника в истории океана, поднятый дайверами с глубины. Эмаль сохранилась целиком, режущая кромка не сточена и не подправлена."
  },
  {
    "id": "R–0604",
    "href": "../16_product_promos/exhibit.html?id=cave-bear-skeleton",
    "world": "grand",
    "worldLabel": "Монументы",
    "category": "Мамонтовая фауна",
    "period": "Плейстоцен",
    "era": "Кайнозой",
    "region": "Европа",
    "name": "Скелет пещерного медведя",
    "latin": "Ursus spelaeus",
    "meta": "Россия, более 12 000 лет<br>Длина 295 см, вес около 150 кг",
    "price": "Цена по запросу",
    "img": "ph_cavebear",
    "priceValue": null,
    "slug": "cave-bear-skeleton",
    "age": "более 12 000 лет, плейстоцен",
    "location": "Россия",
    "size": "Длина 295 см, вес около 150 кг",
    "mount": "Стальной штырь на чернёном основании",
    "description": "Полный смонтированный скелет пещерного медведя — доисторического вида, вымершего около 15 000 лет назад. Высота почти три метра делает наш экземпляр одним из крупнейших представителей вида."
  },
  {
    "id": "R–0605",
    "href": "../16_product_promos/exhibit.html?id=mammoth-skull-tusks",
    "world": "grand",
    "worldLabel": "Монументы",
    "category": "Мамонтовая фауна",
    "period": "Плейстоцен",
    "era": "Кайнозой",
    "region": "Россия",
    "name": "Череп мамонта с бивнями",
    "latin": "Mammuthus primigenius",
    "meta": "Якутия, Россия, ≈ 30 000 лет<br>Размах бивней 2,4 м",
    "price": "7 400 000 ₽",
    "img": "ph_mammoth_skull",
    "priceValue": 7400000,
    "slug": "mammoth-skull-tusks",
    "age": "≈ 30 000 лет",
    "location": "Якутия, Россия",
    "size": "Размах бивней 2,4 м",
    "mount": "Гранитный блок, бронзовые опоры",
    "description": "Череп с полной парой бивней карамельной патины из вечной мерзлоты. Легальное происхождение, полный пакет экспертиз."
  },
  {
    "id": "R–0607",
    "world": "grand",
    "worldLabel": "Монументы",
    "category": "Мамонтовая фауна",
    "period": "Плейстоцен",
    "era": "Кайнозой",
    "region": "Россия",
    "name": "Пара бивней мамонта",
    "latin": "Mammuthus primigenius",
    "meta": "Якутия, Россия, 10–40 тыс лет<br>250 см, общий вес пары 74 кг",
    "price": "Цена по запросу",
    "img": "ph_mammoth_tusks",
    "priceValue": null,
    "slug": "0607-mammuthus-primigenius",
    "age": "10–40 тыс лет, поздний плейстоцен",
    "location": "Якутия, Россия",
    "size": "Длина по наружной дуге 250 см, общий вес пары 74 кг",
    "mount": "Деревянные постаменты с резными люльками",
    "description": "Симметричная пара бивней шерстистого мамонта из якутской мерзлоты — редкий случай: два бивня, сохранившие природную патину и глубокий изгиб. Монтируются на парных подставках как единая скульптурная композиция.",
    "href": "../16_product_promos/mammoth-tusks.html"
  },
  {
    "id": "R–0608",
    "world": "grand",
    "worldLabel": "Монументы",
    "category": "Мамонтовая фауна",
    "period": "Плейстоцен",
    "era": "Кайнозой",
    "region": "Россия",
    "name": "Череп шерстистого носорога",
    "latin": "Coelodonta antiquitatis",
    "meta": "Якутия, Россия, 50–150 тыс лет<br>130 × 82 × 35 см",
    "price": "Цена по запросу",
    "img": "ph_rhino_skull",
    "priceValue": null,
    "slug": "0608-coelodonta-antiquitatis",
    "age": "50–150 тыс лет, четвертичный период",
    "location": "Якутия, Россия",
    "size": "130 × 82 × 35 см",
    "mount": "Постамент дома под вес экспоната",
    "description": "Полный череп шерстистого носорога с сохранёнными рогами и зубным рядом. Coelodonta — символ ледниковой Евразии; черепа, сохранившие оба рога и полный зубной ряд, встречаются редко.",
    "href": "../16_product_promos/rhino-skull.html"
  },
  {
    "id": "R–0208",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Саблезубые кошки",
    "period": "Неоген",
    "era": "Кайнозой",
    "region": "Китай",
    "name": "Череп саблезубой кошки",
    "latin": "Machairodus sp.",
    "meta": "Ганьсу, Китай, 5,3–11,6 млн лет<br>39 × 23 × 14 см",
    "price": "Цена по запросу",
    "img": "ph_sabertooth",
    "priceValue": null,
    "slug": "0208-machairodus-sp",
    "age": "5,3–11,6 млн лет, неоген",
    "location": "Провинция Ганьсу, Китай",
    "size": "39 × 23 × 14 см",
    "mount": "Подставка из чернёной стали со штырём",
    "description": "Череп одного из крупнейших саблезубых хищников неогена с клинковидными клыками. Экспонируется на музейной стойке — редкий предок «саблезубого тигра».",
    "href": "../16_product_promos/sabertooth-skull.html"
  },
  {
    "id": "R–0209",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Ископаемые рыбы",
    "period": "Девон",
    "era": "Палеозой",
    "region": "—",
    "name": "Панцирная рыба Bothriolepis",
    "latin": "Bothriolepis sp.",
    "meta": "≈ 350 млн лет<br>50 см",
    "price": "Цена по запросу",
    "img": "ph_bothriolepis",
    "priceValue": null,
    "slug": "0209-bothriolepis-sp",
    "age": "≈ 350 млн лет, девон",
    "location": "Девонские отложения, происхождение уточняется",
    "size": "50 см",
    "mount": "Стальной штырь на прямоугольном основании",
    "description": "Панцирная рыба девона — одно из первых существ, «одевших» тело в костяную броню. Плита с рельефным отпечатком; готовится авторская подставка.",
    "href": "../16_product_promos/bothriolepis.html"
  },
  {
    "id": "R–0103",
    "world": "cosmos",
    "worldLabel": "Космос",
    "category": "Метеориты",
    "period": "До зарождения жизни",
    "era": "До зарождения жизни",
    "region": "Россия",
    "name": "Метеорит Дронино",
    "latin": "Dronino Iron",
    "meta": "Рязанская область, Россия, ≈ 4,5 млрд лет",
    "price": "Цена по запросу",
    "img": "ph_dronino",
    "priceValue": null,
    "slug": "0103-dronino-iron",
    "age": "≈ 4,5 млрд лет",
    "location": "Рязанская область, Россия",
    "found": "2000 г.",
    "size": "По запросу",
    "mount": "Оформление по запросу клиента",
    "description": "Железный метеорит-атаксит с глубоким рельефом регмаглиптов — следами оплавления в атмосфере. Индивидуалы Дронино ценятся за «дикую», ничем не тронутую форму.",
    "href": "../16_product_promos/meteorite-dronino.html"
  },
  {
    "id": "R–0104",
    "world": "cosmos",
    "worldLabel": "Космос",
    "category": "Метеориты",
    "period": "До зарождения жизни",
    "era": "До зарождения жизни",
    "region": "Россия",
    "name": "Метеорит Чинге",
    "latin": "Chinga Iron",
    "meta": "Чинге, Тыва, Россия, ≈ 4,5 млрд лет",
    "price": "Цена по запросу",
    "img": "ph_chinge",
    "priceValue": null,
    "slug": "0104-chinga-iron",
    "age": "≈ 4,5 млрд лет",
    "location": "Река Чинге, Тыва, Россия",
    "size": "По запросу",
    "mount": "Музейная стойка",
    "description": "Богатый никелем железный метеорит (атаксит) с тёмной корой. Экспонируется на музейной стойке; скульптурная форма обломка не повторяется ни у одного другого.",
    "href": "../16_product_promos/meteorite-chinge.html"
  },
  {
    "id": "R–0105",
    "world": "cosmos",
    "worldLabel": "Космос",
    "category": "Метеориты",
    "period": "До зарождения жизни",
    "era": "До зарождения жизни",
    "region": "Луна",
    "name": "Лунный метеорит в раме",
    "latin": "Lunar meteorite",
    "meta": "Луна, ≈ 4,5 млрд лет",
    "price": "Цена по запросу",
    "img": "ph_moon_frame",
    "priceValue": null,
    "slug": "0105-lunar-meteorite",
    "age": "≈ 4,5 млрд лет",
    "location": "Лунная поверхность, выброшен ударом астероида",
    "size": "По запросу",
    "mount": "Кабинетная рама, настольная или настенная",
    "description": "Обломок лунной коры, выбитый в космос ударом астероида и упавший на Землю, — в одной раме с фотографией полной Луны.",
    "href": "../16_product_promos/lunar-frame.html"
  },
  {
    "id": "R–0211",
    "href": "../16_product_promos/exhibit.html?id=0211-arietites",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Аммониты",
    "period": "Юра",
    "era": "Мезозой",
    "region": "Франция",
    "name": "Аммонит Arietites",
    "latin": "Arietites sp.",
    "meta": "Франция, ≈ 199–193 млн лет<br>Диаметр 42 см, общая высота 44 см с породой",
    "price": "Цена по запросу",
    "img": "ph_arietites",
    "priceValue": null,
    "slug": "0211-arietites",
    "age": "≈ 199–193 млн лет, ранняя юра (синемюр)",
    "location": "Франция",
    "size": "Диаметр 42 см, общая высота 44 см с породой",
    "mount": "Природная порода как основание",
    "description": "Крупный раннеюрский аммонит рода Arietites с широко раскрытой спиралью и мощными радиальными рёбрами. Необычный зеленовато-серый оттенок и контрастная полировка подчёркивают рельеф раковины — редкий по размеру и выразительности объект."
  },
  {
    "id": "R–0212",
    "href": "../16_product_promos/exhibit.html?id=0212-keichousaurus-hui",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Морские рептилии",
    "period": "Триас",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Скелет кейхозавра",
    "latin": "Keichousaurus hui",
    "meta": "Гуйчжоу, Китай, ≈ 245 млн лет<br>Плита 35,4 × 22,5 см, длина скелета 30,5 см",
    "price": "Цена по запросу",
    "img": "ph_keichousaurus",
    "priceValue": null,
    "slug": "0212-keichousaurus-hui",
    "age": "≈ 245 млн лет, триасовый период",
    "location": "Гуйчжоу, Китай",
    "size": "Плита 35,4 × 22,5 см, длина скелета 30,5 см",
    "mount": "Плита породы, вертикальная подача",
    "description": "Keichousaurus hui — небольшой морской завроптеригий с удлинённой шеей, компактным туловищем и конечностями, приспособленными к плаванию. Полный сочленённый скелет на тёмной плите; крупный экземпляр для своего рода."
  },
  {
    "id": "R–0213",
    "href": "../16_product_promos/exhibit.html?id=0213-psittacosaurus-skull",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Динозавры",
    "period": "Мел",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Череп пситтакозавра",
    "latin": "Psittacosaurus sp.",
    "meta": "Ляонин, Китай, ≈ 125 млн лет<br>Череп ≈ 15 см",
    "price": "Цена по запросу",
    "img": "ph_psittacosaurus_skull",
    "priceValue": null,
    "slug": "0213-psittacosaurus-skull",
    "age": "≈ 125 млн лет, ранний мел",
    "location": "Провинция Ляонин, Китай",
    "size": "Череп ≈ 15 см",
    "mount": "Музейная стойка",
    "description": "Череп небольшого растительноядного динозавра Psittacosaurus sp. из группы ранних цератопсов. Высокий короткий череп, клювовидная передняя часть челюстей и выступающие скуловые элементы — характерный портрет «попугайного ящера» раннего мела."
  },
  {
    "id": "R–0214",
    "href": "../16_product_promos/exhibit.html?id=0214-anchiornis-huxleyi",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Динозавры",
    "period": "Юра",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Скелет пернатого динозавра",
    "latin": "Anchiornis huxleyi",
    "meta": "Ляонин, Китай, ≈ 160 млн лет<br>Плита 53,5 × 43 см",
    "price": "Цена по запросу",
    "img": "ph_anchiornis",
    "priceValue": null,
    "slug": "0214-anchiornis-huxleyi",
    "age": "≈ 160 млн лет, поздняя юра",
    "location": "Провинция Ляонин, Китай, формация Тяоцзишань",
    "size": "Плита 53,5 × 43 см",
    "mount": "Плита известняка с фигурным краем",
    "description": "Anchiornis huxleyi — небольшой пернатый паравийный теропод поздней юры, чьё имя означает «почти птица». Находки этого рода сыграли важную роль в изучении происхождения птиц. Сочленённый скелет на плите с читаемыми зубами и когтями."
  },
  {
    "id": "R–0215",
    "href": "../16_product_promos/exhibit.html?id=0215-dinosaur-eggs",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Динозавры",
    "period": "Мел",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Яйца динозавра",
    "latin": "Elongatoolithidae",
    "meta": "Ляонин, Китай, ≈ 89 млн лет<br>Два удлинённых яйца на общей породе",
    "price": "Цена по запросу",
    "img": "ph_dino_eggs",
    "priceValue": null,
    "slug": "0215-dinosaur-eggs",
    "age": "≈ 89 млн лет, поздний мел",
    "location": "Провинция Ляонин, Китай",
    "size": "Два удлинённых яйца на общей породе",
    "mount": "Кованая подставка",
    "description": "Два удлинённых ископаемых яйца группы Elongatoolithidae на общей породе — форма, характерная для овирапторозавров. Выразительная скорлупа с рельефной текстурой, экспонируется на кованой подставке."
  },
  {
    "id": "R–0217",
    "href": "../16_product_promos/exhibit.html?id=0217-dikelokephalina",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Трилобиты",
    "period": "Ордовик",
    "era": "Палеозой",
    "region": "Марокко",
    "name": "Гигантский трилобит",
    "latin": "Dikelokephalina brenchleyi",
    "meta": "Загора, Марокко, ≈ 480–472 млн лет<br>Плита 52,5 × 36,5 см, тело 33,5 × 27 см",
    "price": "Цена по запросу",
    "img": "ph_trilobite_giant",
    "priceValue": null,
    "slug": "0217-dikelokephalina",
    "age": "≈ 480–472 млн лет, ранний ордовик",
    "location": "Загора, Марокко, формация Fezouata",
    "size": "Плита 52,5 × 36,5 см, тело 33,5 × 27 см",
    "mount": "Порода с необработанными краями",
    "description": "Dikelokephalina — род крупных морских трилобитов древней Гондваны. Экземпляр из сланцев Fezouata достигает редкой для трилобитов величины: тело более тридцати сантиметров, глубокий рельеф сегментов на контрастной тёмной плите."
  },
  {
    "id": "R–0610",
    "href": "../16_product_promos/exhibit.html?id=0610-psittacosaurus-skeleton",
    "world": "grand",
    "worldLabel": "Монументы",
    "category": "Динозавры",
    "period": "Мел",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Скелет пситтакозавра",
    "latin": "Psittacosaurus sp.",
    "meta": "Ляонин, Китай, ≈ 125 млн лет<br>168 см",
    "price": "Цена по запросу",
    "img": "ph_psittacosaurus_skeleton",
    "priceValue": null,
    "slug": "0610-psittacosaurus-skeleton",
    "age": "≈ 125 млн лет, ранний мел",
    "location": "Провинция Ляонин, Китай",
    "size": "Смонтированный скелет 168 см, комплектность более 95 %",
    "mount": "Музейная арматура",
    "description": "Полный смонтированный скелет Psittacosaurus sp. — раннего цератопса длиной 168 см. Высокий короткий череп, клювовидные челюсти и длинные задние конечности; комплектность превышает 95 %, подготовка и монтаж рассчитаны на постоянное экспонирование."
  },
  {
    "id": "R–0218",
    "href": "../16_product_promos/exhibit.html?id=0218-mixosaurus-plate",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Морские рептилии",
    "period": "Триас",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Скелет ихтиозавра",
    "latin": "Mixosaurus",
    "meta": "Гуйчжоу, Китай, 242–247 млн лет<br>Плита 58 × 30 см, животное 85 см",
    "price": "Цена по запросу",
    "img": "ph_ichthyosaur_plate",
    "priceValue": null,
    "slug": "0218-mixosaurus-plate",
    "age": "242–247 млн лет, триасовый период",
    "location": "Гуйчжоу, Китай",
    "size": "Плита 58 × 30 см, животное 85 см",
    "mount": "Плита породы, горизонтальная подача",
    "description": "Окаменевший скелет ихтиозавра Mixosaurus, прекрасно сохранившийся в плите из тонкозернистого известняка: череп, позвоночник и элементы грудной клетки в анатомической связи. Редкая и ценная палеонтологическая находка."
  },
  {
    "id": "R–0219",
    "href": "../16_product_promos/exhibit.html?id=0219-dunkleosteus",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Ископаемые рыбы",
    "period": "Девон",
    "era": "Палеозой",
    "region": "—",
    "name": "Череп Dunkleosteus",
    "latin": "Dunkleosteus terrelli",
    "meta": "≈ 360 млн лет",
    "price": "Цена по запросу",
    "img": "ph_dunkleosteus",
    "priceValue": null,
    "slug": "0219-dunkleosteus",
    "age": "≈ 360 млн лет, поздний девон",
    "location": "Реконструкция по научным данным",
    "size": "По запросу",
    "mount": "Подставка из чернёной стали на штырях",
    "description": "Реконструкция черепа и головного щита крупной панцирной рыбы позднего девона. Массивные костные пластины образовывали защитную броню; вместо зубов — острые режущие костные кромки."
  },
  {
    "id": "R–0220",
    "href": "../16_product_promos/exhibit.html?id=0220-spinosaurus-jaw",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Динозавры",
    "period": "Мел",
    "era": "Мезозой",
    "region": "Марокко",
    "name": "Челюсть спинозавра",
    "latin": "Spinosaurus aegyptiacus",
    "meta": "Северная Африка, 100–94 млн лет, сеноман",
    "price": "Цена по запросу",
    "img": "ph_spinosaurus_jaw",
    "priceValue": null,
    "slug": "0220-spinosaurus-jaw",
    "age": "100–94 млн лет, сеноман, поздний мел",
    "location": "Северная Африка",
    "size": "По запросу",
    "mount": "Кованая дугообразная стальная люлька",
    "description": "Фрагмент нижней челюсти Spinosaurus aegyptiacus — крупнейшего хищного теропода Северной Африки. Удлинённые конические зубы почти круглого сечения были приспособлены для удержания скользкой добычи."
  },
  {
    "id": "R–0221",
    "href": "../16_product_promos/exhibit.html?id=0221-carcharodontosaurus-claw",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Динозавры",
    "period": "Мел",
    "era": "Мезозой",
    "region": "Марокко",
    "name": "Коготь крупного теропода",
    "latin": "Carcharodontosaurus sp.",
    "meta": "Северная Африка, 100–94 млн лет, сеноман<br>≈ 26 см",
    "price": "Цена по запросу",
    "img": "ph_carcharodont_claw",
    "priceValue": null,
    "slug": "0221-carcharodontosaurus-claw",
    "age": "100–94 млн лет, сеноман, поздний мел",
    "location": "Северная Африка",
    "size": "≈ 26 см",
    "mount": "Металлическая подставка",
    "description": "Крупная когтевая фаланга Carcharodontosaurus sp. — одного из крупнейших хищных динозавров сеноманского века. Костная основа рогового чехла: при жизни коготь был длиннее и острее."
  },
  {
    "id": "R–0222",
    "href": "../16_product_promos/exhibit.html?id=0222-pterosaur-plate",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Динозавры",
    "period": "Мел",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Скелет птерозавра на плите",
    "latin": "Pterosauria indet.",
    "meta": "Ляонин, Китай, ≈ 125 млн лет<br>Сочленённый скелет на каменной плите",
    "price": "Цена по запросу",
    "img": "ph_pterosaur",
    "priceValue": null,
    "slug": "0222-pterosaur-plate",
    "age": "≈ 125 млн лет, ранний мел",
    "location": "Провинция Ляонин, Китай",
    "size": "Сочленённый скелет на каменной плите",
    "mount": "Настенный или напольный монтаж плиты",
    "description": "Сочленённый ископаемый скелет летающего ящера: вытянутый зубастый череп, лёгкий осевой скелет и сильно удлинённый четвёртый палец, поддерживавший крыло. Требует экспертизы для точной атрибуции."
  },
  {
    "id": "R–0223",
    "href": "../16_product_promos/exhibit.html?id=0223-afrovenator-model",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Динозавры",
    "period": "Юра",
    "era": "Мезозой",
    "region": "Нигер",
    "name": "Модель черепа Afrovenator",
    "latin": "Afrovenator abakensis",
    "meta": "Агадес, Нигер, прообраз 167–161 млн лет<br>Модель черепа ≈ 80–90 см",
    "price": "Цена по запросу",
    "img": "ph_afrovenator",
    "priceValue": null,
    "slug": "0223-afrovenator-model",
    "age": "прообраз 167–161 млн лет, средняя–поздняя юра",
    "location": "Прообраз — Агадес, Нигер, авторская модель",
    "size": "Полноразмерная модель черепа ≈ 80–90 см",
    "mount": "Стальной штырь на чернёном основании",
    "description": "Полноразмерная реконструкция черепа хищного теропода Afrovenator abakensis — «африканского охотника» из формации Тиурарен. Авторская модель по эталонному экземпляру вида; череп воспроизведён в натуральную величину."
  },
  {
    "id": "R–0611",
    "href": "../16_product_promos/exhibit.html?id=0611-coelodonta-skeleton",
    "world": "grand",
    "worldLabel": "Монументы",
    "category": "Мамонтовая фауна",
    "period": "Плейстоцен",
    "era": "Кайнозой",
    "region": "Россия",
    "name": "Скелет шерстистого носорога",
    "latin": "Coelodonta antiquitatis",
    "meta": "Якутия, Россия, 50–150 тыс лет<br>Полный скелет",
    "price": "Цена по запросу",
    "img": "ph_rhino_skeleton",
    "priceValue": null,
    "slug": "0611-coelodonta-skeleton",
    "age": "50–150 тыс лет, плейстоцен",
    "location": "Якутия, Россия",
    "size": "Полный скелет",
    "mount": "Профессиональная сборка на скрытом каркасе",
    "description": "Полный смонтированный скелет шерстистого носорога с характерным массивным телосложением и крупными рогами. Обнаружен в Якутии; профессиональная сборка на скрытом стальном каркасе."
  },
  {
    "id": "R–0612",
    "href": "../16_product_promos/exhibit.html?id=0612-crocodyliformes",
    "world": "grand",
    "worldLabel": "Монументы",
    "category": "Морские рептилии",
    "period": "Мел",
    "era": "Мезозой",
    "region": "—",
    "name": "Скелет крокодилиформа",
    "latin": "Crocodyliformes indet.",
    "meta": "мезозой<br>Около 6 м",
    "price": "Цена по запросу",
    "img": "ph_crocodyliform",
    "priceValue": null,
    "slug": "0612-crocodyliformes",
    "age": "мезозой, длиннорылая форма",
    "location": "Составной скелет, провенанс уточняется",
    "size": "Около 6 м",
    "mount": "Металлические опоры, сборка на месте",
    "description": "Составной скелет крупного длиннорылого крокодилиформа, подготовленный для музейного монтажа: череп, позвоночный столб, рёбра, конечности и хвост на металлических опорах."
  },
  {
    "id": "R–0224",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Аммониты",
    "period": "Мезозой",
    "era": "Мезозой",
    "region": "Россия",
    "name": "Аммониты полированные",
    "latin": "Ammonitida",
    "meta": "Россия, мезозой<br>7 предметов",
    "price": "Цена по запросу",
    "img": "ph_ammonite_studio",
    "priceValue": null,
    "slug": "0224-polished-ammonites",
    "age": "252–66 млн лет, мезозой",
    "location": "Россия",
    "size": "Набор из 7 предметов",
    "mount": "Кованые ажурные подставки чёрного металла",
    "description": "Комплект из семи полированных и фигурных аммонитов: срезы с раскрытыми камерами раковины и цельные экземпляры с перламутровой поверхностью. Предметы подбираются поштучно, состав комплекта согласовывается. Съёмка сделана с крупнейшего предмета комплекта.",
    "href": "../16_product_promos/exhibit.html?id=0224-polished-ammonites"
  },
  {
    "id": "R–0231",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Морские лилии",
    "period": "Триас",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Морская лилия",
    "latin": "Traumatocrinus guanlingensis",
    "meta": "Раскрытый веер, Китай, триас<br>Под заказ",
    "price": "Цена по запросу",
    "img": "ph_crinoid_fan",
    "priceValue": null,
    "slug": "0231-crinoid-fan",
    "age": "≈ 235 млн лет, триас",
    "location": "Юньнань-Гуйчжоу, Китай",
    "size": "По запросу",
    "mount": "Плита на стальной подставке",
    "status": "Под заказ",
    "description": "Крупный раскрытый веер Traumatocrinus на цельной плите — парадный экземпляр серии.",
    "href": "../16_product_promos/exhibit.html?id=0231-crinoid-fan"
  },
  {
    "id": "R–0232",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Морские лилии",
    "period": "Триас",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Морская лилия",
    "latin": "Traumatocrinus guanlingensis",
    "meta": "Круглая крона, Китай, триас<br>Под заказ",
    "price": "Цена по запросу",
    "img": "ph_crinoid_round",
    "priceValue": null,
    "slug": "0232-crinoid-round",
    "age": "≈ 235 млн лет, триас",
    "location": "Юньнань-Гуйчжоу, Китай",
    "size": "По запросу",
    "mount": "Плита на стальной подставке",
    "status": "Под заказ",
    "description": "Редкая подача: крона раскрыта полным кругом, руки читаются до кончиков.",
    "href": "../16_product_promos/exhibit.html?id=0232-crinoid-round"
  },
  {
    "id": "R–0233",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Морские лилии",
    "period": "Триас",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Морская лилия",
    "latin": "Traumatocrinus guanlingensis",
    "meta": "Веер в раме, Китай, триас<br>Под заказ",
    "price": "Цена по запросу",
    "img": "ph_crinoid_frame_fan",
    "priceValue": null,
    "slug": "0233-crinoid-frame-fan",
    "age": "≈ 235 млн лет, триас",
    "location": "Юньнань-Гуйчжоу, Китай",
    "size": "По запросу",
    "mount": "Деревянная рама",
    "status": "Под заказ",
    "description": "Веер на прямом стебле в деревянной раме — готовый кабинетный объект.",
    "href": "../16_product_promos/exhibit.html?id=0233-crinoid-frame-fan"
  },
  {
    "id": "R–0234",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Морские лилии",
    "period": "Триас",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Морская лилия",
    "latin": "Traumatocrinus guanlingensis",
    "meta": "Бутон в раме, Китай, триас<br>Под заказ",
    "price": "Цена по запросу",
    "img": "ph_crinoid_bud",
    "priceValue": null,
    "slug": "0234-crinoid-bud",
    "age": "≈ 235 млн лет, триас",
    "location": "Юньнань-Гуйчжоу, Китай",
    "size": "По запросу",
    "mount": "Деревянная рама",
    "status": "Под заказ",
    "description": "Сомкнутая крона на изящно изогнутом стебле — самый графичный экземпляр серии.",
    "href": "../16_product_promos/exhibit.html?id=0234-crinoid-bud"
  },
  {
    "id": "R–0235",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Морские лилии",
    "period": "Триас",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Морская лилия",
    "latin": "Traumatocrinus guanlingensis",
    "meta": "Высокий веер в раме, Китай, триас<br>Под заказ",
    "price": "Цена по запросу",
    "img": "ph_crinoid_tall",
    "priceValue": null,
    "slug": "0235-crinoid-tall",
    "age": "≈ 235 млн лет, триас",
    "location": "Юньнань-Гуйчжоу, Китай",
    "size": "По запросу",
    "mount": "Деревянная рама",
    "status": "Под заказ",
    "description": "Высокая вертикальная композиция: веер венчает стебель во всю плиту.",
    "href": "../16_product_promos/exhibit.html?id=0235-crinoid-tall"
  },
  {
    "id": "R–0236",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Морские лилии",
    "period": "Триас",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Морская лилия",
    "latin": "Traumatocrinus guanlingensis",
    "meta": "Крона и малые кроны, Китай, триас<br>Под заказ",
    "price": "Цена по запросу",
    "img": "ph_crinoid_floats",
    "priceValue": null,
    "slug": "0236-crinoid-floats",
    "age": "≈ 235 млн лет, триас",
    "location": "Юньнань-Гуйчжоу, Китай",
    "size": "По запросу",
    "mount": "Деревянная рама",
    "status": "Под заказ",
    "description": "Взрослая крона и рядом — малые кроны той же колонии, редкий групповой сюжет.",
    "href": "../16_product_promos/exhibit.html?id=0236-crinoid-floats"
  },
  {
    "id": "R–0237",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Морские лилии",
    "period": "Триас",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Морская лилия",
    "latin": "Traumatocrinus guanlingensis",
    "meta": "Два стебля в раме, Китай, триас<br>Под заказ",
    "price": "Цена по запросу",
    "img": "ph_crinoid_pair",
    "priceValue": null,
    "slug": "0237-crinoid-pair",
    "age": "≈ 235 млн лет, триас",
    "location": "Юньнань-Гуйчжоу, Китай",
    "size": "По запросу",
    "mount": "Деревянная рама",
    "status": "Под заказ",
    "description": "Два стебля уходят параллельно вниз — строгая, почти каллиграфическая плита.",
    "href": "../16_product_promos/exhibit.html?id=0237-crinoid-pair"
  },
  {
    "id": "R–0238",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Морские лилии",
    "period": "Триас",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Морская лилия",
    "latin": "Traumatocrinus guanlingensis",
    "meta": "Изогнутый стебель в раме, Китай, триас<br>Под заказ",
    "price": "Цена по запросу",
    "img": "ph_crinoid_arc",
    "priceValue": null,
    "slug": "0238-crinoid-arc",
    "age": "≈ 235 млн лет, триас",
    "location": "Юньнань-Гуйчжоу, Китай",
    "size": "По запросу",
    "mount": "Деревянная рама",
    "status": "Под заказ",
    "description": "Стебель входит в кадр дугой из угла — динамичная композиция для кабинета.",
    "href": "../16_product_promos/exhibit.html?id=0238-crinoid-arc"
  },
  {
    "id": "R–0239",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Морские лилии",
    "period": "Триас",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Морская лилия",
    "latin": "Traumatocrinus guanlingensis",
    "meta": "Малый веер, Китай, триас<br>Под заказ",
    "price": "Цена по запросу",
    "img": "ph_crinoid_small_fan",
    "priceValue": null,
    "slug": "0239-crinoid-small-fan",
    "age": "≈ 235 млн лет, триас",
    "location": "Юньнань-Гуйчжоу, Китай",
    "size": "По запросу",
    "mount": "Плита на стальной подставке",
    "status": "Под заказ",
    "description": "Камерный экземпляр: небольшой веер, склонённый набок, для настольной подачи.",
    "href": "../16_product_promos/exhibit.html?id=0239-crinoid-small-fan"
  },
  {
    "id": "R–0240",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Морские лилии",
    "period": "Триас",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Морская лилия",
    "latin": "Traumatocrinus guanlingensis",
    "meta": "Колония на высокой плите, Китай, триас<br>Под заказ",
    "price": "Цена по запросу",
    "img": "ph_crinoid_colony_tall",
    "priceValue": null,
    "slug": "0240-crinoid-colony-tall",
    "age": "≈ 235 млн лет, триас",
    "location": "Юньнань-Гуйчжоу, Китай",
    "size": "По запросу",
    "mount": "Плита на стальной подставке",
    "status": "Под заказ",
    "description": "Высокая плита с целой колонией — десятки крон на тонких стеблях.",
    "href": "../16_product_promos/exhibit.html?id=0240-crinoid-colony-tall"
  },
  {
    "id": "R–0241",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Морские лилии",
    "period": "Триас",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Морская лилия",
    "latin": "Traumatocrinus guanlingensis",
    "meta": "Колония, Китай, триас<br>Под заказ",
    "price": "Цена по запросу",
    "img": "ph_crinoid_colony",
    "priceValue": null,
    "slug": "0241-crinoid-colony",
    "age": "≈ 235 млн лет, триас",
    "location": "Юньнань-Гуйчжоу, Китай",
    "size": "По запросу",
    "mount": "Плита на стальной подставке",
    "status": "Под заказ",
    "description": "Колония, расходящаяся из одного узла, — сцена дрейфа, застывшая целиком.",
    "href": "../16_product_promos/exhibit.html?id=0241-crinoid-colony"
  },
  {
    "id": "R–0242",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Морские лилии",
    "period": "Триас",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Морская лилия",
    "latin": "Traumatocrinus guanlingensis",
    "meta": "Группа крон, Китай, триас<br>Под заказ",
    "price": "Цена по запросу",
    "img": "ph_crinoid_group",
    "priceValue": null,
    "slug": "0242-crinoid-group",
    "age": "≈ 235 млн лет, триас",
    "location": "Юньнань-Гуйчжоу, Китай",
    "size": "По запросу",
    "mount": "Плита на стальной подставке",
    "status": "Под заказ",
    "description": "Группа крон на плите свободной формы — самый скульптурный экземпляр.",
    "href": "../16_product_promos/exhibit.html?id=0242-crinoid-group"
  },
  {
    "id": "R–0243",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Морские лилии",
    "period": "Триас",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Морская лилия",
    "latin": "Traumatocrinus guanlingensis",
    "meta": "Скопление, Китай, триас<br>Под заказ",
    "price": "Цена по запросу",
    "img": "ph_crinoid_cluster",
    "priceValue": null,
    "slug": "0243-crinoid-cluster",
    "age": "≈ 235 млн лет, триас",
    "location": "Юньнань-Гуйчжоу, Китай",
    "size": "По запросу",
    "mount": "Плита на стальной подставке",
    "status": "Под заказ",
    "description": "Плотное переплетение крон и стеблей — фактура, которую хочется разглядывать.",
    "href": "../16_product_promos/exhibit.html?id=0243-crinoid-cluster"
  },
  {
    "id": "R–0244",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Морские лилии",
    "period": "Триас",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Морская лилия",
    "latin": "Traumatocrinus guanlingensis",
    "meta": "Три кроны, Китай, триас<br>Под заказ",
    "price": "Цена по запросу",
    "img": "ph_crinoid_trio",
    "priceValue": null,
    "slug": "0244-crinoid-trio",
    "age": "≈ 235 млн лет, триас",
    "location": "Юньнань-Гуйчжоу, Китай",
    "size": "По запросу",
    "mount": "Плита на стальной подставке",
    "status": "Под заказ",
    "description": "Три кроны в одном кадре камня — ритмичная вертикальная плита.",
    "href": "../16_product_promos/exhibit.html?id=0244-crinoid-trio"
  },
  {
    "id": "R–0230",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Морские рептилии",
    "period": "Триас",
    "era": "Мезозой",
    "region": "Китай",
    "name": "Скелет нотозавра на плите",
    "latin": "Nothosaurus sp.",
    "meta": "Китай, ≈ 240 млн лет<br>Плита 151,5 × 58 см",
    "price": "Цена по запросу",
    "img": "ph_nothosaurus",
    "priceValue": null,
    "status": "Под заказ",
    "slug": "0230-nothosaurus",
    "age": "≈ 240 млн лет, средний триас",
    "location": "Китай",
    "size": "Плита 58 × 151,5 × 4 см, вес 140 кг",
    "mount": "Плита на стальном настенном креплении",
    "description": "Морская рептилия триаса на цельной сланцевой плите: скелет от вытянутого зубастого черепа до длинного хвоста лежит рельефом в камне, кость глубокого чёрного тона контрастирует с серой породой. Единственный объект коллекции, поставляемый под заказ.",
    "href": "../16_product_promos/exhibit.html?id=0230-nothosaurus"
  },
  {
    "id": "R–0229",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Пещерные львы",
    "period": "Плейстоцен",
    "era": "Кайнозой",
    "region": "Евразия",
    "name": "Череп пещерного льва",
    "latin": "Panthera leo spelaea",
    "meta": "Евразия, плейстоцен<br>40 × 30 × 28 см",
    "price": "Цена по запросу",
    "img": "ph_cave_lion_vitrine",
    "priceValue": null,
    "slug": "0229-cave-lion-skull-vitrine",
    "age": "2,6 млн – 11 тыс лет, плейстоцен",
    "location": "Евразия",
    "size": "40 × 30 × 28 см",
    "mount": "Стеклянная витрина на чёрном основании, опора из чернёной стали",
    "description": "Полный череп пещерного льва с нижней челюстью, смонтированный в раскрытой позе на стальной опоре. Кость минерализована до тёплого бурого тона, сохранены оба верхних и оба нижних клыка и зубной ряд. Объект поставляется в собственной стеклянной витрине на чёрном основании — его не нужно ничем дополнять.",
    "href": "../16_product_promos/exhibit.html?id=0229-cave-lion-skull-vitrine"
  },
  {
    "id": "R–0228",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Пещерные львы",
    "period": "Плейстоцен",
    "era": "Кайнозой",
    "region": "Россия",
    "name": "Череп пещерного льва",
    "latin": "Panthera leo spelaea",
    "meta": "Евразия, плейстоцен",
    "price": "Цена по запросу",
    "img": "ph_cave_lion2",
    "priceValue": null,
    "slug": "0228-cave-lion-skull-2",
    "age": "2,6 млн – 11 тыс лет, плейстоцен",
    "location": "Евразия",
    "size": "По запросу",
    "mount": "Подставка из чернёной стали",
    "description": "Кость глубоко минерализована — тон уходит от охры к тёмно-бурому, поверхность держит сеть древних трещин. Сохранены клыки, зубной ряд и высокий гребень черепной коробки; подача фронтальная, на подставке из чернёной стали.",
    "href": "../16_product_promos/exhibit.html?id=0228-cave-lion-skull-2"
  },
  {
    "id": "R–0226",
    "world": "vita",
    "worldLabel": "Жизнь",
    "category": "Гиены",
    "period": "Неоген",
    "era": "Кайнозой",
    "region": "Азия",
    "name": "Череп динокрокуты",
    "latin": "Dinocrocuta gigantea",
    "meta": "Азия, миоцен",
    "price": "Цена по запросу",
    "img": "ph_hyena_skull",
    "priceValue": null,
    "slug": "0226-hyena-skull",
    "age": "23–5,3 млн лет, миоцен",
    "location": "Азия",
    "size": "По запросу",
    "mount": "Породное основание, постамент под заказ",
    "description": "Череп динокрокуты — гигантского хищника миоцена, обитавшего в Азии и Африке. Внешне похожая на гиену, Dinocrocuta обладала самыми мощными челюстями своего времени: короткая высокая морда и крупные конические зубы дробили кости крупной добычи. Череп этой особи крупнее, чем у пещерного медведя.",
    "href": "../16_product_promos/exhibit.html?id=0226-hyena-skull"
  },
  {
    "id": "R–0227",
    "world": "cosmos",
    "worldLabel": "Космос",
    "category": "Метеориты",
    "period": "До зарождения жизни",
    "era": "До зарождения жизни",
    "region": "Россия",
    "name": "Метеорит Дронино, 128 кг",
    "latin": "Dronino Iron",
    "meta": "Рязанская область, Россия, ≈ 4,5 млрд лет<br>128 кг",
    "price": "Цена по запросу",
    "img": "ph_dronino128",
    "priceValue": null,
    "slug": "0227-dronino-128kg",
    "age": "≈ 4,5 млрд лет",
    "location": "Рязанская область, Россия",
    "size": "128 кг",
    "mount": "Массивный металлический постамент",
    "description": "Железный метеорит Дронино массой сто двадцать восемь килограммов — один из самых крупных найденных экземпляров этого падения. Монументальный объект космического происхождения на авторской подставке.",
    "href": "../16_product_promos/exhibit.html?id=0227-dronino-128kg"
  },
  {
    "id": "R–0613",
    "world": "grand",
    "worldLabel": "Монументы",
    "category": "Динозавры",
    "period": "Мел",
    "era": "Мезозой",
    "region": "Монголия",
    "name": "Скелет пинакозавра",
    "latin": "Pinacosaurus",
    "meta": "Центральная Азия, около 80–75 млн лет",
    "price": "Цена по запросу",
    "img": "ph_pinacosaurus",
    "priceValue": null,
    "slug": "0613-pinacosaurus",
    "age": "около 80–75 млн лет, поздний мел",
    "location": "Центральная Азия",
    "size": "По запросу",
    "mount": "Низкая плита из чернёной стали, вертикальные стойки",
    "description": "Смонтированный скелет пинакозавра — панцирного динозавра (анкилозавра) позднего мела. Костные пластины-остеодермы вдоль спины и характерный низкий силуэт; скелет смонтирован на скрытом стальном каркасе.",
    "href": "../16_product_promos/exhibit.html?id=0613-pinacosaurus"
  },
  {
    "id": "R–0614",
    "world": "grand",
    "worldLabel": "Монументы",
    "category": "Динозавры",
    "period": "Мел",
    "era": "Мезозой",
    "region": "Монголия",
    "name": "Скелет овираптора",
    "latin": "Oviraptoridae",
    "meta": "Центральная Азия, 89,8–70,6 млн лет",
    "price": "Цена по запросу",
    "img": "ph_oviraptor",
    "priceValue": null,
    "slug": "0614-oviraptor",
    "age": "89,8–70,6 млн лет, поздний мел",
    "location": "Центральная Азия",
    "size": "По запросу",
    "mount": "Музейная арматура",
    "description": "Полный смонтированный скелет овираптора — пернатого динозавра-теропода позднего мела с характерным беззубым клювом и лёгким сложением. Динамичная поза, музейный монтаж.",
    "href": "../16_product_promos/exhibit.html?id=0614-oviraptor"
  },
  {
    "id": "R–0615",
    "world": "grand",
    "worldLabel": "Монументы",
    "category": "Мамонтовая фауна",
    "period": "Плейстоцен",
    "era": "Кайнозой",
    "region": "Россия",
    "name": "Скелет степного зубра",
    "latin": "Bison priscus",
    "meta": "Россия, 2,5 млн – 10 тыс лет",
    "price": "Цена по запросу",
    "img": "ph_bison_skeleton",
    "priceValue": null,
    "slug": "0615-bison-priscus",
    "age": "2,5 млн – 10 тыс лет назад, плейстоцен",
    "location": "Россия",
    "size": "Рога с размахом более метра, полные размеры по запросу",
    "mount": "Реставрация и монтаж под заказ",
    "description": "Скелет степного зубра Bison priscus — исполина мамонтовой степи. Жил от 2,5 млн до 10 тыс лет назад; самцы достигали двух тонн веса и более двух метров в холке, а размах длинных загнутых вверх рогов превышал метр. Сейчас это подлинный комплект костей: реставрация и музейная сборка выполняются под заказ, поза и подача согласовываются с вами — кадры сборки показывают, каким станет экспонат.",
    "href": "../16_product_promos/exhibit.html?id=0615-bison-priscus"
  },
  {
    "id": "R–0616",
    "world": "grand",
    "worldLabel": "Монументы",
    "category": "Мамонтовая фауна",
    "period": "Плейстоцен",
    "era": "Кайнозой",
    "region": "Россия",
    "name": "Скелет плейстоценового волка",
    "latin": "Canis lupus",
    "meta": "Россия, плейстоцен",
    "price": "Цена по запросу",
    "img": "ph_pleistocene_wolf",
    "priceValue": null,
    "slug": "0616-pleistocene-wolf",
    "age": "2,6 млн – 11 тыс лет, плейстоцен",
    "location": "Россия",
    "size": "По запросу",
    "mount": "Низкий подиум",
    "description": "Скелет плейстоценового волка — хищника ледниковой Евразии, современника мамонта и шерстистого носорога. Собран для постоянного экспонирования в тематической коллекции ледникового периода.",
    "href": "../16_product_promos/exhibit.html?id=0616-pleistocene-wolf"
  },
  {
    "id": "R–0617",
    "world": "grand",
    "worldLabel": "Монументы",
    "category": "Мамонтовая фауна",
    "period": "Плейстоцен",
    "era": "Кайнозой",
    "region": "Россия",
    "name": "Скелет мамонта",
    "latin": "Mammuthus primigenius",
    "meta": "Якутия, Россия, плейстоцен",
    "price": "Цена по запросу",
    "img": "ph_mammoth_skeleton",
    "priceValue": null,
    "slug": "0617-mammoth-skeleton",
    "age": "2,6 млн – 11 тыс лет, плейстоцен",
    "location": "Якутия, Россия",
    "size": "По запросу",
    "mount": "Скрытый стальной каркас, монтаж на месте",
    "description": "Полный скелет шерстистого мамонта — самый крупный смонтированный экспонат коллекции: задаёт масштаб всему помещению. Монтаж на скрытом стальном каркасе, установка командой дома.",
    "href": "../16_product_promos/exhibit.html?id=0617-mammoth-skeleton"
  }
];
